// <auto-generated />
using System;
using HullSizingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HullSizingService.Migrations
{
    [DbContext(typeof(SizingDbContext))]
    [Migration("20251127213454_AddWeightBreakdownJsonToCandidateDesigns")]
    partial class AddWeightBreakdownJsonToCandidateDesigns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sizing")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Sizing.CandidateDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("bm");

                    b.Property<string>("BowFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bow_family");

                    b.Property<decimal>("Cb")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("cb");

                    b.Property<decimal?>("Cm")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("cm");

                    b.Property<decimal>("Cp")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("cp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Cwp")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("cwp");

                    b.Property<decimal>("DM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("dm");

                    b.Property<decimal>("DisplacementT")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("displacement_t");

                    b.Property<decimal?>("EhpKw")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ehp_kw");

                    b.Property<int?>("FamilyMaskVersion")
                        .HasColumnType("integer")
                        .HasColumnName("family_mask_version");

                    b.Property<string>("FlagsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("flags_json");

                    b.Property<decimal>("Fn")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("fn");

                    b.Property<string>("GeometryGenerationError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("geometry_generation_error");

                    b.Property<int>("GeometryGenerationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("geometry_generation_status");

                    b.Property<string>("GeometryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry_json");

                    b.Property<decimal?>("GmEstM")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("gm_est_m");

                    b.Property<string>("HullFamily")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hull_family");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.Property<decimal?>("KbM")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("kb_m");

                    b.Property<decimal?>("LcbPctLpp")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("lcb_pct_lpp");

                    b.Property<decimal>("LoaM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("loa_m");

                    b.Property<decimal>("LppM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("lpp_m");

                    b.Property<decimal>("LwlM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("lwl_m");

                    b.Property<decimal?>("LwlOverLambda")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("lwl_over_lambda");

                    b.Property<string>("MidshipFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("midship_family");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("ReferenceVesselId")
                        .HasColumnType("text")
                        .HasColumnName("reference_vessel_id");

                    b.Property<string>("ReferenceVesselName")
                        .HasColumnType("text")
                        .HasColumnName("reference_vessel_name");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("score");

                    b.Property<string>("ScoresJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("scores_json");

                    b.Property<string>("ShipdParametersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("shipd_parameters_json");

                    b.Property<decimal?>("ShpKw")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("shp_kw");

                    b.Property<decimal?>("SimilarityScore")
                        .HasColumnType("numeric")
                        .HasColumnName("similarity_score");

                    b.Property<Guid>("SizingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("sizing_run_id");

                    b.Property<string>("SolverMode")
                        .HasColumnType("text")
                        .HasColumnName("solver_mode");

                    b.Property<string>("SternFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stern_family");

                    b.Property<decimal>("TM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("tm");

                    b.Property<string>("VesselCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vessel_category");

                    b.Property<string>("VesselType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vessel_type");

                    b.Property<string>("WeightBreakdownJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("weight_breakdown_json");

                    b.HasKey("Id")
                        .HasName("pk_candidate_designs");

                    b.HasIndex("HullFamily")
                        .HasDatabaseName("ix_candidate_designs_hull_family");

                    b.HasIndex("Rank")
                        .HasDatabaseName("ix_candidate_designs_rank");

                    b.HasIndex("Score")
                        .IsDescending()
                        .HasDatabaseName("ix_candidate_designs_score");

                    b.HasIndex("SizingRunId")
                        .HasDatabaseName("ix_candidate_designs_sizing_run_id");

                    b.ToTable("candidate_designs", "sizing");
                });

            modelBuilder.Entity("Shared.Models.Sizing.HullFamilyPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BOverTMax")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("b_over_t_max");

                    b.Property<decimal>("BOverTMin")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("b_over_t_min");

                    b.Property<decimal>("CbMax")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("cb_max");

                    b.Property<decimal>("CbMin")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("cb_min");

                    b.Property<decimal?>("CpMax")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("cp_max");

                    b.Property<decimal?>("CpMin")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("cp_min");

                    b.Property<decimal?>("CwpMax")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("cwp_max");

                    b.Property<decimal?>("CwpMin")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("cwp_min");

                    b.Property<decimal>("DOverTMax")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("d_over_t_max");

                    b.Property<decimal>("DOverTMin")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("d_over_t_min");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("family");

                    b.Property<decimal?>("FnMax")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("fn_max");

                    b.Property<decimal?>("FnMin")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("fn_min");

                    b.Property<string>("GeneratorType")
                        .HasColumnType("text")
                        .HasColumnName("generator_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("LOverBMax")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("l_over_b_max");

                    b.Property<decimal>("LOverBMin")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("l_over_b_min");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id")
                        .HasName("pk_hull_family_presets");

                    b.HasIndex("Family")
                        .IsUnique()
                        .HasDatabaseName("ix_hull_family_presets_family");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_hull_family_presets_is_active")
                        .HasFilter("is_active = true");

                    b.ToTable("hull_family_presets", "sizing");
                });

            modelBuilder.Entity("Shared.Models.Sizing.IsoContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("container_type");

                    b.Property<int>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<int>("LengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("length_mm");

                    b.Property<int>("MaxGrossKg")
                        .HasColumnType("integer")
                        .HasColumnName("max_gross_kg");

                    b.Property<int>("WidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("width_mm");

                    b.HasKey("Id")
                        .HasName("pk_iso_containers");

                    b.ToTable("iso_containers", "sizing");
                });

            modelBuilder.Entity("Shared.Models.Sizing.KpiWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metric");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_kpi_weights");

                    b.HasIndex("UserId", "Metric")
                        .IsUnique()
                        .HasDatabaseName("ix_kpi_weights_user_id_metric");

                    b.ToTable("kpi_weights", "sizing");
                });

            modelBuilder.Entity("Shared.Models.Sizing.MissionCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BowFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bow_family");

                    b.Property<decimal?>("CapAirdraftM")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("cap_airdraft_m");

                    b.Property<decimal?>("CapBeamM")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("cap_beam_m");

                    b.Property<decimal?>("CapDraftM")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("cap_draft_m");

                    b.Property<decimal?>("CapLoaM")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("cap_loa_m");

                    b.Property<string>("CargoBasis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cargo_basis");

                    b.Property<decimal?>("CargoDensityTPerM3")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("cargo_density_t_per_m3");

                    b.Property<decimal?>("CargoValue")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cargo_value");

                    b.Property<decimal?>("CargoVolumeM3")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cargo_volume_m3");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("EnduranceNm")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("endurance_nm");

                    b.Property<decimal?>("EnvHsM")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("env_hs_m");

                    b.Property<decimal?>("EnvTzS")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("env_tz_s");

                    b.Property<int?>("FamilyMaskVersion")
                        .HasColumnType("integer")
                        .HasColumnName("family_mask_version");

                    b.Property<string>("MidshipFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("midship_family");

                    b.Property<string>("MissionCategory")
                        .HasColumnType("text")
                        .HasColumnName("mission_category");

                    b.Property<string>("MissionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mission_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("SeaMarginPct")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("sea_margin_pct");

                    b.Property<decimal>("ServiceMarginPct")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("service_margin_pct");

                    b.Property<decimal>("ServiceSpeedKn")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("service_speed_kn");

                    b.Property<string>("ShipdInputsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("shipd_inputs_json");

                    b.Property<string>("SternFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stern_family");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TeuCount")
                        .HasColumnType("integer")
                        .HasColumnName("teu_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mission_cases");

                    b.HasIndex("MissionType")
                        .HasDatabaseName("ix_mission_cases_mission_type")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_mission_cases_tenant_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mission_cases_user_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_mission_cases_name_tenant_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("mission_cases", "sizing");
                });

            modelBuilder.Entity("Shared.Models.Sizing.PushOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid")
                        .HasColumnName("vessel_id");

                    b.HasKey("Id")
                        .HasName("pk_push_operations");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_push_operations_candidate_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_push_operations_idempotency_key");

                    b.ToTable("push_operations", "sizing");
                });

            modelBuilder.Entity("Shared.Models.Sizing.SizingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BowFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bow_family");

                    b.Property<int?>("ComputeTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("compute_time_ms");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("text")
                        .HasColumnName("diagnostics_json");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("FamilyMaskVersion")
                        .HasColumnType("integer")
                        .HasColumnName("family_mask_version");

                    b.Property<string>("LocksJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("locks_json");

                    b.Property<string>("MidshipFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("midship_family");

                    b.Property<Guid>("MissionCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("mission_case_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<string>("ShipdInputVectorJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("shipd_input_vector_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SternFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stern_family");

                    b.Property<string>("VesselCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vessel_category");

                    b.Property<string>("VesselType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vessel_type");

                    b.HasKey("Id")
                        .HasName("pk_sizing_runs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_sizing_runs_created_at");

                    b.HasIndex("MissionCaseId")
                        .HasDatabaseName("ix_sizing_runs_mission_case_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sizing_runs_status");

                    b.ToTable("sizing_runs", "sizing");
                });

            modelBuilder.Entity("Shared.Models.Sizing.VesselCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("bm");

                    b.Property<decimal?>("Cb")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("cb");

                    b.Property<decimal?>("Cm")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("cm");

                    b.Property<decimal?>("Cp")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("cp");

                    b.Property<decimal?>("Cwp")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("cwp");

                    b.Property<decimal?>("DM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("dm");

                    b.Property<decimal?>("DwtT")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("dwt_t");

                    b.Property<string>("LicenseInfo")
                        .HasColumnType("text")
                        .HasColumnName("license_info");

                    b.Property<decimal?>("LppM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("lpp_m");

                    b.Property<decimal?>("LwlM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("lwl_m");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Provenance")
                        .HasColumnType("text")
                        .HasColumnName("provenance");

                    b.Property<decimal?>("ServiceSpeedKn")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("service_speed_kn");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<decimal?>("TM")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("tm");

                    b.Property<string>("VesselType")
                        .HasColumnType("text")
                        .HasColumnName("vessel_type");

                    b.HasKey("Id")
                        .HasName("pk_vessel_catalog");

                    b.HasIndex("Provenance")
                        .HasDatabaseName("ix_vessel_catalog_provenance");

                    b.HasIndex("VesselType")
                        .HasDatabaseName("ix_vessel_catalog_vessel_type");

                    b.ToTable("vessel_catalog", "sizing");
                });

            modelBuilder.Entity("Shared.Models.Sizing.CandidateDesign", b =>
                {
                    b.HasOne("Shared.Models.Sizing.SizingRun", "SizingRun")
                        .WithMany("Candidates")
                        .HasForeignKey("SizingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_designs_sizing_runs_sizing_run_id");

                    b.Navigation("SizingRun");
                });

            modelBuilder.Entity("Shared.Models.Sizing.PushOperation", b =>
                {
                    b.HasOne("Shared.Models.Sizing.CandidateDesign", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_operations_candidate_designs_candidate_id");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Shared.Models.Sizing.SizingRun", b =>
                {
                    b.HasOne("Shared.Models.Sizing.MissionCase", "MissionCase")
                        .WithMany("SizingRuns")
                        .HasForeignKey("MissionCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sizing_runs_mission_cases_mission_case_id");

                    b.Navigation("MissionCase");
                });

            modelBuilder.Entity("Shared.Models.Sizing.MissionCase", b =>
                {
                    b.Navigation("SizingRuns");
                });

            modelBuilder.Entity("Shared.Models.Sizing.SizingRun", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
