using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using HullSizingService.Services.Integration;
using Shared.DTOs.ShipD;
using Shared.DTOs.Sizing;
using Shared.Models.Sizing;

namespace HullSizingService.Services.ShipD;

/// <summary>
/// Temporary adapter that maps mission cases to ShipD parameter vectors.
/// This implementation uses placeholder logic until full ShipD metadata ingestion is completed.
/// </summary>
public class ShipDParameterAdapter : IShipDParameterAdapter
{
    private const int ShipDParameterCount = 45;

    private readonly ILogger<ShipDParameterAdapter> _logger;
    private readonly IDataServiceClient _dataServiceClient;

    public ShipDParameterAdapter(
        ILogger<ShipDParameterAdapter> logger,
        IDataServiceClient dataServiceClient)
    {
        _logger = logger;
        _dataServiceClient = dataServiceClient;
    }

    public async Task<ShipDParameterizationResult> BuildAsync(
        MissionCase missionCase,
        CreateSizingRunDto runRequest,
        CancellationToken cancellationToken = default)
    {
        // Fetch metadata (best-effort; fall back to local defaults if unavailable)
        var parameterMetadataTask = _dataServiceClient.GetShipDParameterMetadataAsync(cancellationToken);
        var taxonomyTask = _dataServiceClient.GetShipDVesselTaxonomyAsync(cancellationToken);
        await Task.WhenAll(parameterMetadataTask, taxonomyTask);

        var parameterMetadata = parameterMetadataTask.Result;
        var taxonomy = taxonomyTask.Result;

        // Use incoming selections when available; otherwise fall back to mission defaults.
        var vesselCategory = (runRequest.VesselCategory ?? missionCase.MissionCategory ?? "commercial").ToLowerInvariant();
        var vesselType = (runRequest.VesselType ?? missionCase.MissionType).ToLowerInvariant();
        var bowFamily = runRequest.BowFamily ?? missionCase.BowFamily;
        var midshipFamily = runRequest.MidshipFamily ?? missionCase.MidshipFamily;
        var sternFamily = runRequest.SternFamily ?? missionCase.SternFamily;
        var maskVersion = runRequest.FamilyMaskVersion ?? missionCase.FamilyMaskVersion ?? 1;

        var taxonomyEntry = taxonomy.FirstOrDefault(t =>
            string.Equals(t.Category, vesselCategory, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(t.Type, vesselType, StringComparison.OrdinalIgnoreCase));

        // Placeholder vector: start with zeros and inject a few normalized mission hints.
        var vector = Enumerable.Repeat(0m, ShipDParameterCount).ToArray();
        var warnings = new List<string>();

        if (!string.IsNullOrWhiteSpace(runRequest.ShipdInputVectorJson))
        {
            try
            {
                var overrideVector = JsonSerializer.Deserialize<List<decimal>>(runRequest.ShipdInputVectorJson);
                if (overrideVector != null && overrideVector.Count == ShipDParameterCount)
                {
                    vector = overrideVector.ToArray();
                }
                else
                {
                    warnings.Add("Provided ShipD input vector did not contain 45 entries; using autogenerated defaults.");
                }
            }
            catch (JsonException ex)
            {
                warnings.Add("Provided ShipD input vector could not be parsed; using autogenerated defaults.");
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to parse user-supplied ShipD vector. Falling back to autogenerated defaults.");
            }
        }
        if (missionCase.CapLoaM.HasValue && missionCase.CapLoaM.Value > 0)
        {
            vector[0] = Math.Clamp(missionCase.CapLoaM.Value / 300m, 0.0m, 1.0m);
        }

        if (missionCase.CapBeamM.HasValue && missionCase.CapBeamM.Value > 0)
        {
            vector[7] = Math.Clamp(missionCase.CapBeamM.Value / 50m, 0.0m, 1.0m);
        }

        if (missionCase.ServiceSpeedKn > 0)
        {
            vector[20] = Math.Clamp(missionCase.ServiceSpeedKn / 40m, 0.0m, 1.0m);
        }

        // Extract additionalParameters from MissionCase.ShipdInputsJson as fallback if not in request
        // This must happen BEFORE applying taxonomy defaults so user values can override defaults
        IDictionary<string, object>? effectiveAdditionalParameters = runRequest.Options?.AdditionalParameters;
        if ((effectiveAdditionalParameters == null || effectiveAdditionalParameters.Count == 0) &&
            !string.IsNullOrWhiteSpace(missionCase.ShipdInputsJson))
        {
            try
            {
                var shipdInputs = JsonSerializer.Deserialize<Dictionary<string, object>>(missionCase.ShipdInputsJson);
                if (shipdInputs != null && shipdInputs.TryGetValue("additionalParameters", out var additionalParamsObj))
                {
                    if (additionalParamsObj is JsonElement jsonElement)
                    {
                        effectiveAdditionalParameters = JsonSerializer.Deserialize<Dictionary<string, object>>(jsonElement.GetRawText());
                    }
                    else if (additionalParamsObj is Dictionary<string, object> dict)
                    {
                        effectiveAdditionalParameters = dict;
                    }
                    else
                    {
                        var json = JsonSerializer.Serialize(additionalParamsObj);
                        effectiveAdditionalParameters = JsonSerializer.Deserialize<Dictionary<string, object>>(json);
                    }

                    if (effectiveAdditionalParameters != null && effectiveAdditionalParameters.Count > 0)
                    {
                        _logger.LogDebug("[SHIPD_ADAPTER] Extracted {Count} additional parameters from MissionCase.ShipdInputsJson as fallback",
                            effectiveAdditionalParameters.Count);
                    }
                }
            }
            catch (JsonException ex)
            {
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to extract additionalParameters from MissionCase.ShipdInputsJson as fallback");
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Unexpected error extracting additionalParameters from MissionCase.ShipdInputsJson");
            }
        }

        // Extract bow/stern length ratio defaults from taxonomy
        decimal? defaultBow = null;
        decimal? defaultStern = null;
        if (taxonomyEntry != null && !string.IsNullOrWhiteSpace(taxonomyEntry.AdditionalParametersJson))
        {
            try
            {
                var taxonomyParams = JsonSerializer.Deserialize<Dictionary<string, object>>(taxonomyEntry.AdditionalParametersJson);
                if (taxonomyParams != null)
                {
                    if (taxonomyParams.TryGetValue("bowLengthRatio", out var bowObj) && bowObj != null)
                    {
                        defaultBow = ExtractDecimalValue(bowObj);
                        _logger.LogDebug("[SHIPD_ADAPTER] Extracted taxonomy default bow length ratio: {Ratio}", defaultBow);
                    }
                    if (taxonomyParams.TryGetValue("sternLengthRatio", out var sternObj) && sternObj != null)
                    {
                        defaultStern = ExtractDecimalValue(sternObj);
                        _logger.LogDebug("[SHIPD_ADAPTER] Extracted taxonomy default stern length ratio: {Ratio}", defaultStern);
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to parse bow/stern defaults from taxonomy AdditionalParametersJson");
            }
        }
        else if (taxonomyEntry == null)
        {
            _logger.LogWarning("[SHIPD_ADAPTER] No taxonomy entry found for category '{Category}' and type '{Type}' - cannot extract bow/stern defaults", vesselCategory, vesselType);
        }
        else
        {
            _logger.LogWarning("[SHIPD_ADAPTER] Taxonomy entry found but AdditionalParametersJson is empty - cannot extract bow/stern defaults");
        }

        // Apply taxonomy defaults when available
        if (taxonomyEntry != null)
        {
            if (bowFamily == null && taxonomyEntry.BowFamilies.Count > 0)
            {
                bowFamily = taxonomyEntry.BowFamilies.First();
                warnings.Add($"Bow family defaulted to '{bowFamily}' from taxonomy.");
            }

            if (midshipFamily == null && taxonomyEntry.MidshipFamilies.Count > 0)
            {
                midshipFamily = taxonomyEntry.MidshipFamilies.First();
                warnings.Add($"Midship family defaulted to '{midshipFamily}' from taxonomy.");
            }

            if (sternFamily == null && taxonomyEntry.SternFamilies.Count > 0)
            {
                sternFamily = taxonomyEntry.SternFamilies.First();
                warnings.Add($"Stern family defaulted to '{sternFamily}' from taxonomy.");
            }
        }
        else
        {
            warnings.Add($"No taxonomy entry found for category '{vesselCategory}' and type '{vesselType}'.");
        }

        if (bowFamily is null || midshipFamily is null || sternFamily is null)
        {
            warnings.Add("One or more hull families were not specified; using defaults during ShipD processing.");
        }

        // Apply taxonomy defaults for bow/stern length ratios if not provided by user
        // This must happen before ApplyConditionalParameters so user overrides can take precedence
        ShipDAdditionalParameters? additionalParsed = null;
        bool hasUserBowRatio = false;
        bool hasUserSternRatio = false;

        if (effectiveAdditionalParameters != null && effectiveAdditionalParameters.Count > 0)
        {
            try
            {
                var json = JsonSerializer.Serialize(effectiveAdditionalParameters);
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                    PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                };
                additionalParsed = JsonSerializer.Deserialize<ShipDAdditionalParameters>(json, options);
                hasUserBowRatio = additionalParsed?.BowLengthRatio.HasValue == true;
                hasUserSternRatio = additionalParsed?.SternLengthRatio.HasValue == true;
                _logger.LogDebug("[SHIPD_ADAPTER] Parsed AdditionalParameters for defaults check. BowLengthRatio: {Bow}, SternLengthRatio: {Stern}, HasUserBow: {HasBow}, HasUserStern: {HasStern}",
                    additionalParsed?.BowLengthRatio, additionalParsed?.SternLengthRatio, hasUserBowRatio, hasUserSternRatio);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to parse AdditionalParameters for defaults check. Will try in ApplyConditionalParameters.");
            }
        }

        // Apply taxonomy defaults if user hasn't provided values
        // Check both additionalParsed and vector[1]/vector[2] to ensure we don't override existing values
        if (defaultBow.HasValue && !hasUserBowRatio && vector[1] == 0m)
        {
            vector[1] = defaultBow.Value;
            _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied taxonomy default bow length ratio: {Ratio} to vector[1]", defaultBow.Value);
        }
        else if (defaultBow.HasValue && hasUserBowRatio)
        {
            _logger.LogDebug("[SHIPD_ADAPTER] Skipped taxonomy default bow length ratio (user provided: {UserValue})", additionalParsed?.BowLengthRatio);
        }
        else if (defaultBow.HasValue && vector[1] != 0m)
        {
            _logger.LogDebug("[SHIPD_ADAPTER] Skipped taxonomy default bow length ratio (vector[1] already set: {Value})", vector[1]);
        }
        else if (!defaultBow.HasValue)
        {
            _logger.LogWarning("[SHIPD_ADAPTER] ⚠️ No taxonomy default for bow length ratio available");
        }

        if (defaultStern.HasValue && !hasUserSternRatio && vector[2] == 0m)
        {
            vector[2] = defaultStern.Value;
            _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied taxonomy default stern length ratio: {Ratio} to vector[2]", defaultStern.Value);
        }
        else if (defaultStern.HasValue && hasUserSternRatio)
        {
            _logger.LogDebug("[SHIPD_ADAPTER] Skipped taxonomy default stern length ratio (user provided: {UserValue})", additionalParsed?.SternLengthRatio);
        }
        else if (defaultStern.HasValue && vector[2] != 0m)
        {
            _logger.LogDebug("[SHIPD_ADAPTER] Skipped taxonomy default stern length ratio (vector[2] already set: {Value})", vector[2]);
        }
        else if (!defaultStern.HasValue)
        {
            _logger.LogWarning("[SHIPD_ADAPTER] ⚠️ No taxonomy default for stern length ratio available");
        }

        // Apply family-specific defaults from taxonomy (e.g., bit_BB for bulbous_bow, Atrans for transom_stern)
        if (taxonomyEntry != null && !string.IsNullOrWhiteSpace(taxonomyEntry.AdditionalParametersJson))
        {
            try
            {
                var taxonomyParams = JsonSerializer.Deserialize<Dictionary<string, object>>(taxonomyEntry.AdditionalParametersJson);
                if (taxonomyParams != null && taxonomyParams.TryGetValue("familyDefaults", out var familyDefaultsObj))
                {
                    Dictionary<string, Dictionary<string, object>>? familyDefaults = null;
                    if (familyDefaultsObj is JsonElement jsonElement)
                    {
                        familyDefaults = JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, object>>>(jsonElement.GetRawText());
                    }
                    else if (familyDefaultsObj is Dictionary<string, Dictionary<string, object>> dict)
                    {
                        familyDefaults = dict;
                    }

                    if (familyDefaults != null)
                    {
                        // Apply bow family defaults
                        if (!string.IsNullOrEmpty(bowFamily) && familyDefaults.TryGetValue(bowFamily, out var bowDefaults))
                        {
                            ApplyFamilyDefaults(vector, bowDefaults, "bow", bowFamily, parameterMetadata, warnings);
                        }

                        // Apply midship family defaults
                        if (!string.IsNullOrEmpty(midshipFamily) && familyDefaults.TryGetValue(midshipFamily, out var midDefaults))
                        {
                            ApplyFamilyDefaults(vector, midDefaults, "midship", midshipFamily, parameterMetadata, warnings);
                        }

                        // Apply stern family defaults
                        if (!string.IsNullOrEmpty(sternFamily) && familyDefaults.TryGetValue(sternFamily, out var sternDefaults))
                        {
                            ApplyFamilyDefaults(vector, sternDefaults, "stern", sternFamily, parameterMetadata, warnings);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to apply family-specific defaults from taxonomy");
            }
        }

        // CRITICAL FIX: Apply hardcoded family defaults if taxonomy doesn't provide them
        // This ensures different family selections always produce visually distinct hull shapes
        _logger.LogInformation("[SHIPD_ADAPTER] Applying hardcoded family defaults as fallback: bow={Bow}, midship={Mid}, stern={Stern}",
            bowFamily ?? "none", midshipFamily ?? "none", sternFamily ?? "none");
        ApplyHardcodedBowFamilyDefaults(vector, bowFamily, parameterMetadata);
        ApplyHardcodedSternFamilyDefaults(vector, sternFamily, parameterMetadata);
        ApplyHardcodedMidshipFamilyDefaults(vector, midshipFamily, parameterMetadata);

        // Apply conditional parameters from AdditionalParameters (using effectiveAdditionalParameters)
        ApplyConditionalParameters(
            vector,
            effectiveAdditionalParameters,
            bowFamily,
            midshipFamily,
            sternFamily,
            parameterMetadata,
            warnings);

        IDictionary<string, object>? additional = effectiveAdditionalParameters;

        if (!string.IsNullOrWhiteSpace(taxonomyEntry?.AdditionalParametersJson))
        {
            try
            {
                var taxonomyParams = JsonSerializer.Deserialize<Dictionary<string, object>>(taxonomyEntry.AdditionalParametersJson);
                if (taxonomyParams != null)
                {
                    additional ??= new Dictionary<string, object>();
                    foreach (var pair in taxonomyParams)
                    {
                        additional[pair.Key] = pair.Value;
                    }
                }
            }
            catch (JsonException ex)
            {
                warnings.Add("Failed to parse additional taxonomy parameters.");
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Could not parse AdditionalParametersJson for taxonomy entry {Category}/{Type}", vesselCategory, vesselType);
            }
        }

        var labels = parameterMetadata.Count == ShipDParameterCount
            ? parameterMetadata
                .OrderBy(p => p.ParameterIndex)
                .Select(p => p.Label)
                .ToArray()
            : Enumerable.Range(0, ShipDParameterCount)
                .Select(i => $"param_{i:00}")
                .ToArray();

        _logger.LogDebug(
            "[SHIPD_ADAPTER] Generated ShipD vector (maskVersion={MaskVersion}) for category={Category}, type={Type}, bow={Bow}, mid={Mid}, stern={Stern}. Payload={Payload}",
            maskVersion,
            vesselCategory,
            vesselType,
            bowFamily,
            midshipFamily,
            sternFamily,
            JsonSerializer.Serialize(vector));

        var result = new ShipDParameterizationResult(
            ParameterVector: vector,
            ParameterLabels: labels,
            VesselCategory: vesselCategory,
            VesselType: vesselType,
            BowFamily: bowFamily,
            MidshipFamily: midshipFamily,
            SternFamily: sternFamily,
            MaskVersion: maskVersion,
            AdditionalParameters: additional,
            Warnings: warnings);

        return result;
    }

    /// <summary>
    /// Applies conditional parameters from AdditionalParameters to the ShipD vector.
    /// Maps user inputs to ShipD parameter indices based on selected families.
    /// </summary>
    private void ApplyConditionalParameters(
        decimal[] vector,
        IDictionary<string, object>? additionalParameters,
        string? bowFamily,
        string? midshipFamily,
        string? sternFamily,
        IReadOnlyList<ShipDParameterMetadataDto> metadata,
        List<string> warnings)
    {
        if (additionalParameters == null || additionalParameters.Count == 0)
        {
            return;
        }

        // Try to deserialize as ShipDAdditionalParameters
        // Use camelCase naming policy to match frontend JSON
        ShipDAdditionalParameters? additional = null;
        try
        {
            var json = JsonSerializer.Serialize(additionalParameters);
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase
            };
            additional = JsonSerializer.Deserialize<ShipDAdditionalParameters>(json, options);
            _logger.LogDebug("[SHIPD_ADAPTER] Successfully deserialized AdditionalParameters. BowLengthRatio: {Bow}, SternLengthRatio: {Stern}",
                additional?.BowLengthRatio, additional?.SternLengthRatio);
        }
        catch (JsonException ex)
        {
            _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to deserialize AdditionalParameters as ShipDAdditionalParameters. Attempting manual mapping.");
        }

        if (additional == null)
        {
            // Fallback: try manual mapping from dictionary
            ApplyConditionalParametersFromDictionary(vector, additionalParameters, bowFamily, midshipFamily, sternFamily, metadata, warnings);
            return;
        }

        // Section Geometry (Image 1)
        if (additional.FlareAngleDeg.HasValue)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == 8); // Beta
            if (param != null)
            {
                vector[8] = NormalizeValue(additional.FlareAngleDeg.Value, param.Min, param.Max, param.Mean, param.StdDev);
                _logger.LogDebug("[SHIPD_ADAPTER] Applied flare angle: {Flare}° (normalized: {Normalized})", additional.FlareAngleDeg.Value, vector[8]);
            }
        }

        if (additional.DeadriseAngleDeg.HasValue)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == 19); // Cdrft
            if (param != null)
            {
                vector[19] = NormalizeValue(additional.DeadriseAngleDeg.Value, param.Min, param.Max, param.Mean, param.StdDev);
                _logger.LogDebug("[SHIPD_ADAPTER] Applied deadrise angle: {Deadrise}° (normalized: {Normalized})", additional.DeadriseAngleDeg.Value, vector[19]);
            }
        }

        // Chine type affects Rc (index 9) and Rk (index 10)
        if (!string.IsNullOrEmpty(additional.ChineType))
        {
            if (additional.ChineType.Equals("hard", StringComparison.OrdinalIgnoreCase))
            {
                // Hard chine: sharper transition, lower Rc, higher Rk
                vector[9] = 0.2m;  // Lower curvature
                vector[10] = 0.8m; // Higher knuckle
                _logger.LogDebug("[SHIPD_ADAPTER] Applied hard chine: Rc=0.2, Rk=0.8");
            }
            else if (additional.ChineType.Equals("soft", StringComparison.OrdinalIgnoreCase))
            {
                // Soft chine: rounded transition, higher Rc, lower Rk
                vector[9] = 0.6m;  // Higher curvature
                vector[10] = 0.3m; // Lower knuckle
                _logger.LogDebug("[SHIPD_ADAPTER] Applied soft chine: Rc=0.6, Rk=0.3");
            }
        }

        // Tumblehome toggle (bit_EP_T, index 21)
        if (additional.TumblehomeEnabled == true && midshipFamily == "fine_midship")
        {
            vector[21] = 1.0m;
            _logger.LogDebug("[SHIPD_ADAPTER] Enabled tumblehome for fine_midship");
        }

        // Longitudinal Segmentation (Image 2)
        if (additional.BowLengthRatio.HasValue)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == 1); // Lb
            if (param != null)
            {
                vector[1] = Math.Clamp(additional.BowLengthRatio.Value, param.Min ?? 0m, param.Max ?? 1m);
                _logger.LogDebug("[SHIPD_ADAPTER] Applied bow length ratio: {Ratio} (clamped to metadata bounds)", vector[1]);
            }
            else
            {
                // Apply value even if metadata lookup fails (with basic validation)
                vector[1] = Math.Clamp(additional.BowLengthRatio.Value, 0.05m, 0.9m);
                _logger.LogWarning("[SHIPD_ADAPTER] Applied bow length ratio: {Ratio} (metadata lookup failed, using basic bounds)", vector[1]);
            }
        }

        if (additional.SternLengthRatio.HasValue)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == 2); // Ls
            if (param != null)
            {
                vector[2] = Math.Clamp(additional.SternLengthRatio.Value, param.Min ?? 0m, param.Max ?? 1m);
                _logger.LogDebug("[SHIPD_ADAPTER] Applied stern length ratio: {Ratio} (clamped to metadata bounds)", vector[2]);
            }
            else
            {
                // Apply value even if metadata lookup fails (with basic validation)
                vector[2] = Math.Clamp(additional.SternLengthRatio.Value, 0.05m, 0.9m);
                _logger.LogWarning("[SHIPD_ADAPTER] Applied stern length ratio: {Ratio} (metadata lookup failed, using basic bounds)", vector[2]);
            }
        }

        // Validate Lb + Ls < 1.0 (to ensure Lm > 0)
        if (vector[1] + vector[2] >= 1.0m)
        {
            var excess = vector[1] + vector[2] - 0.99m;
            vector[1] = Math.Max(0.05m, vector[1] - excess / 2);
            vector[2] = Math.Max(0.05m, vector[2] - excess / 2);
            warnings.Add($"Adjusted Lb and Ls to ensure Lm > 0 (Lb={vector[1]:F3}, Ls={vector[2]:F3})");
        }

        if (additional.BowRakeAngleDeg.HasValue)
        {
            // Bow rake uses same Beta parameter (index 8) as flare
            // If flare is already set, use the average or prefer rake
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == 8);
            if (param != null)
            {
                if (vector[8] == 0m || !additional.FlareAngleDeg.HasValue)
                {
                    vector[8] = NormalizeValue(additional.BowRakeAngleDeg.Value, param.Min, param.Max, param.Mean, param.StdDev);
                }
                else
                {
                    // Both flare and rake specified - use average
                    var flareNorm = NormalizeValue(additional.FlareAngleDeg.Value, param.Min, param.Max, param.Mean, param.StdDev);
                    var rakeNorm = NormalizeValue(additional.BowRakeAngleDeg.Value, param.Min, param.Max, param.Mean, param.StdDev);
                    vector[8] = (flareNorm + rakeNorm) / 2m;
                }
            }
        }

        if (additional.SternRakeAngleDeg.HasValue)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == 27); // Beta_trans
            if (param != null)
            {
                vector[27] = NormalizeValue(additional.SternRakeAngleDeg.Value, param.Min, param.Max, param.Mean, param.StdDev);
                _logger.LogDebug("[SHIPD_ADAPTER] Applied stern rake angle: {Rake}° (normalized: {Normalized})", additional.SternRakeAngleDeg.Value, vector[27]);
            }
        }

        // Bulb Geometry (Image 3) - only if bulbous_bow or bulbous selected
        // Handle both "bulbous" and "bulbous_bow" family names
        if (bowFamily == "bulbous_bow" || bowFamily == "bulbous")
        {
            // Enable bulb (only if not already set by family defaults)
            if (vector[31] == 0m)
            {
                vector[31] = 1.0m; // bit_BB
            }

            if (additional.BulbLengthRatio.HasValue)
            {
                var param = metadata.FirstOrDefault(m => m.ParameterIndex == 33); // Lbb
                if (param != null)
                {
                    vector[33] = Math.Clamp(additional.BulbLengthRatio.Value, param.Min ?? 0m, param.Max ?? 0.2m);
                }
            }

            if (additional.BulbWidthRatio.HasValue)
            {
                var param = metadata.FirstOrDefault(m => m.ParameterIndex == 35); // Bbb
                if (param != null)
                {
                    vector[35] = Math.Clamp(additional.BulbWidthRatio.Value, param.Min ?? 0m, param.Max ?? 1m);
                }
            }

            if (additional.BulbHeightRatio.HasValue)
            {
                var param = metadata.FirstOrDefault(m => m.ParameterIndex == 34); // Hbb
                if (param != null)
                {
                    vector[34] = Math.Clamp(additional.BulbHeightRatio.Value, param.Min ?? 0m, param.Max ?? 1m);
                }
            }

            if (additional.BulbAsymmetryFactor.HasValue)
            {
                var param = metadata.FirstOrDefault(m => m.ParameterIndex == 36); // Lbbm
                if (param != null)
                {
                    vector[36] = Math.Clamp(additional.BulbAsymmetryFactor.Value, param.Min ?? -1m, param.Max ?? 1m);
                }
            }

            if (additional.BulbFilletRadius.HasValue)
            {
                var param = metadata.FirstOrDefault(m => m.ParameterIndex == 37); // Rbb
                if (param != null)
                {
                    vector[37] = Math.Clamp(additional.BulbFilletRadius.Value, param.Min ?? 0.05m, param.Max ?? 0.33m);
                }
            }

            // Ensure bulb dimensions are set to sensible defaults if they're too small
            // This ensures effective bulb geometry when bulb is enabled
            EnsureSensibleBulbDimensions(vector, metadata);

            _logger.LogDebug("[SHIPD_ADAPTER] Applied bulb geometry for bulbous_bow");
        }
    }

    /// <summary>
    /// Applies family-specific defaults from taxonomy (e.g., bit_BB for bulbous_bow, Atrans for transom_stern).
    /// </summary>
    private void ApplyFamilyDefaults(
        decimal[] vector,
        Dictionary<string, object> familyDefaults,
        string region,
        string familyName,
        IReadOnlyList<ShipDParameterMetadataDto> metadata,
        List<string> warnings)
    {
        foreach (var kvp in familyDefaults)
        {
            try
            {
                var paramName = kvp.Key;
                var paramValue = ExtractDecimalValue(kvp.Value);

                if (!paramValue.HasValue)
                {
                    continue;
                }

                // Map parameter names to ShipD vector indices
                int? paramIndex = paramName.ToLowerInvariant() switch
                {
                    "bit_bb" => 31,      // Bulbous bow flag
                    "bit_sb" => 32,      // Skeg/stern bulb flag (if exists)
                    "atrans" => 22,      // Transom area ratio
                    "beta" => 8,         // Bow flare/rake angle
                    "beta_trans" => 27,  // Stern rake angle
                    "rc" => 9,           // Bow curvature
                    "rc_trans" => 29,    // Stern curvature
                    "rk" => 10,          // Bow knuckle
                    "rk_trans" => 30,    // Stern knuckle
                    "lbb" => 33,         // Bulb length ratio
                    "hbb" => 34,         // Bulb height ratio
                    "bbb" => 35,         // Bulb width ratio
                    "lbbm" => 36,        // Bulb asymmetry
                    "rbb" => 37,         // Bulb fillet radius
                    "cdrft" => 19,       // Deadrise angle
                    _ => null
                };

                if (paramIndex.HasValue)
                {
                    var param = metadata.FirstOrDefault(m => m.ParameterIndex == paramIndex.Value);
                    if (param != null && param.Min.HasValue && param.Max.HasValue)
                    {
                        // Normalize value if needed (some are already 0-1, others are physical units)
                        decimal normalizedValue;
                        if (param.Min.Value >= 0m && param.Max.Value <= 1m)
                        {
                            // Already normalized (0-1 range)
                            normalizedValue = Math.Clamp(paramValue.Value, 0m, 1m);
                        }
                        else
                        {
                            // Physical unit - normalize to 0-1
                            normalizedValue = NormalizeValue(paramValue.Value, param.Min, param.Max, param.Mean, param.StdDev);
                        }

                        // Only apply if vector slot is empty (0) to avoid overriding user values
                        if (vector[paramIndex.Value] == 0m)
                        {
                            vector[paramIndex.Value] = normalizedValue;
                            _logger.LogDebug("[SHIPD_ADAPTER] Applied {Region} family default {ParamName}={Value} (normalized: {Normalized}) to vector[{Index}]",
                                region, paramName, paramValue.Value, normalizedValue, paramIndex.Value);
                        }
                        else
                        {
                            _logger.LogDebug("[SHIPD_ADAPTER] Skipped {Region} family default {ParamName} (vector[{Index}] already set: {Value})",
                                region, paramName, paramIndex.Value, vector[paramIndex.Value]);
                        }
                    }
                    else
                    {
                        // No metadata - apply value as-is if it's a ratio (0-1) or boolean (0/1)
                        if (paramName.ToLowerInvariant().StartsWith("bit_") || paramName.ToLowerInvariant() == "atrans")
                        {
                            // Boolean or ratio parameter - use value as-is
                            if (vector[paramIndex.Value] == 0m)
                            {
                                vector[paramIndex.Value] = Math.Clamp(paramValue.Value, 0m, 1m);
                                _logger.LogDebug("[SHIPD_ADAPTER] Applied {Region} family default {ParamName}={Value} to vector[{Index}] (no metadata)",
                                    region, paramName, paramValue.Value, paramIndex.Value);
                            }
                        }
                    }
                }
                else
                {
                    _logger.LogDebug("[SHIPD_ADAPTER] Unknown family default parameter name: {ParamName} for {Region} family {Family}",
                        paramName, region, familyName);
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to apply family default {Key} for {Region} family {Family}",
                    kvp.Key, region, familyName);
            }
        }
    }

    /// <summary>
    /// Fallback method to apply conditional parameters from dictionary when ShipDAdditionalParameters deserialization fails.
    /// </summary>
    private void ApplyConditionalParametersFromDictionary(
        decimal[] vector,
        IDictionary<string, object> additionalParameters,
        string? bowFamily,
        string? midshipFamily,
        string? sternFamily,
        IReadOnlyList<ShipDParameterMetadataDto> metadata,
        List<string> warnings)
    {
        // Try to extract common parameter names from dictionary
        foreach (var kvp in additionalParameters)
        {
            try
            {
                var key = kvp.Key.ToLowerInvariant();
                var value = Convert.ToDecimal(kvp.Value);

                // Map common parameter names to indices
                switch (key)
                {
                    case "flareangledeg":
                    case "flare_angle_deg":
                    case "flare":
                        var flareParam = metadata.FirstOrDefault(m => m.ParameterIndex == 8);
                        if (flareParam != null)
                        {
                            vector[8] = NormalizeValue(value, flareParam.Min, flareParam.Max, flareParam.Mean, flareParam.StdDev);
                        }
                        break;

                    case "deadriseangledeg":
                    case "deadrise_angle_deg":
                    case "deadrise":
                        var deadriseParam = metadata.FirstOrDefault(m => m.ParameterIndex == 19);
                        if (deadriseParam != null)
                        {
                            vector[19] = NormalizeValue(value, deadriseParam.Min, deadriseParam.Max, deadriseParam.Mean, deadriseParam.StdDev);
                        }
                        break;

                    case "bowlengthratio":
                    case "bow_length_ratio":
                    case "lb":
                        var lbParam = metadata.FirstOrDefault(m => m.ParameterIndex == 1);
                        if (lbParam != null)
                        {
                            vector[1] = Math.Clamp(value, lbParam.Min ?? 0m, lbParam.Max ?? 1m);
                        }
                        else
                        {
                            // Apply value even if metadata lookup fails
                            vector[1] = Math.Clamp(value, 0.05m, 0.9m);
                            _logger.LogWarning("[SHIPD_ADAPTER] Applied bow length ratio from dictionary: {Ratio} (metadata lookup failed)", vector[1]);
                        }
                        break;

                    case "sternlengthratio":
                    case "stern_length_ratio":
                    case "ls":
                        var lsParam = metadata.FirstOrDefault(m => m.ParameterIndex == 2);
                        if (lsParam != null)
                        {
                            vector[2] = Math.Clamp(value, lsParam.Min ?? 0m, lsParam.Max ?? 1m);
                        }
                        else
                        {
                            // Apply value even if metadata lookup fails
                            vector[2] = Math.Clamp(value, 0.05m, 0.9m);
                            _logger.LogWarning("[SHIPD_ADAPTER] Applied stern length ratio from dictionary: {Ratio} (metadata lookup failed)", vector[2]);
                        }
                        break;
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to apply parameter {Key} from AdditionalParameters", kvp.Key);
            }
        }
    }

    /// <summary>
    /// Safely extracts a decimal value from a JSON deserialized object (handles JsonElement, numeric types, etc.)
    /// </summary>
    private decimal? ExtractDecimalValue(object? value)
    {
        if (value == null)
        {
            return null;
        }

        try
        {
            // Handle JsonElement (common when deserializing JSON to Dictionary<string, object>)
            if (value is JsonElement jsonElement)
            {
                try
                {
                    if (jsonElement.ValueKind == JsonValueKind.Number)
                    {
                        return jsonElement.GetDecimal();
                    }
                    else if (jsonElement.ValueKind == JsonValueKind.String)
                    {
                        var str = jsonElement.GetString();
                        if (!string.IsNullOrEmpty(str) && decimal.TryParse(str, out var parsed))
                        {
                            return parsed;
                        }
                    }
                    else if (jsonElement.ValueKind == JsonValueKind.True)
                    {
                        return 1m;
                    }
                    else if (jsonElement.ValueKind == JsonValueKind.False)
                    {
                        return 0m;
                    }
                    // Try to get decimal regardless of ValueKind (handles edge cases)
                    try
                    {
                        return jsonElement.GetDecimal();
                    }
                    catch
                    {
                        // If GetDecimal() fails, try parsing as string
                        var str = jsonElement.GetRawText().Trim('"');
                        if (decimal.TryParse(str, out var parsed))
                        {
                            return parsed;
                        }
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to extract decimal from JsonElement with ValueKind={ValueKind}", jsonElement.ValueKind);
                }
                return null;
            }

            // Handle direct numeric types
            if (value is decimal dec)
            {
                return dec;
            }
            if (value is double dbl)
            {
                return (decimal)dbl;
            }
            if (value is float flt)
            {
                return (decimal)flt;
            }
            if (value is int intVal)
            {
                return (decimal)intVal;
            }
            if (value is long longVal)
            {
                return (decimal)longVal;
            }

            // Try Convert.ToDecimal as fallback
            return Convert.ToDecimal(value);
        }
        catch (Exception)
        {
            // If all conversion attempts fail, return null
            return null;
        }
    }

    /// <summary>
    /// Normalizes a physical value to ShipD's 0-1 range using min/max bounds.
    /// </summary>
    private decimal NormalizeValue(decimal physicalValue, decimal? min, decimal? max, decimal? mean, decimal? stdDev)
    {
        if (!min.HasValue || !max.HasValue || min.Value >= max.Value)
        {
            // Fallback: use mean and stdDev if available
            if (mean.HasValue && stdDev.HasValue && stdDev.Value > 0)
            {
                var normalizedValue = (physicalValue - mean.Value) / (3 * stdDev.Value) + 0.5m;
                return Math.Clamp(normalizedValue, 0m, 1m);
            }
            return 0.5m; // Default to middle
        }

        // Linear normalization: (value - min) / (max - min)
        var normalizedResult = (physicalValue - min.Value) / (max.Value - min.Value);
        return Math.Clamp(normalizedResult, 0m, 1m);
    }

    /// <summary>
    /// Adjusts ShipD vector when principal dimensions change to maintain hull form character.
    /// Uses intelligent scaling to preserve design intent while applying new dimensions.
    /// </summary>
    public decimal[] AdjustVectorForDimensionChange(
        decimal[] originalVector,
        decimal oldLpp,
        decimal newLpp,
        decimal oldBeam,
        decimal newBeam,
        decimal oldDraft,
        decimal newDraft,
        IReadOnlyList<ShipDParameterMetadataDto> metadata)
    {
        var adjusted = (decimal[])originalVector.Clone();

        // Scale longitudinal proportions to maintain absolute lengths
        var lengthRatio = newLpp / oldLpp;
        if (Math.Abs(lengthRatio - 1.0m) > 0.05m)
        {
            // Adjust Lb, Ls to maintain absolute bow/stern lengths
            adjusted[1] = Math.Clamp(adjusted[1] * oldLpp / newLpp, 0.05m, 0.45m); // Lb
            adjusted[2] = Math.Clamp(adjusted[2] * oldLpp / newLpp, 0.05m, 0.45m); // Ls

            _logger.LogDebug(
                "[SHIPD_ADAPTER] Scaled longitudinal proportions for length change {Old}m → {New}m: Lb={Lb}, Ls={Ls}",
                oldLpp, newLpp, adjusted[1], adjusted[2]);
        }

        // Scale beam-related angles to maintain form
        var beamRatio = newBeam / oldBeam;
        if (Math.Abs(beamRatio - 1.0m) > 0.05m)
        {
            // Reduce flare angles if beam increases (maintain hull character)
            var beamScaleFactor = (decimal)Math.Pow((double)(oldBeam / newBeam), 0.5);
            adjusted[8] *= beamScaleFactor;  // Beta (bow flare)
            adjusted[27] *= beamScaleFactor; // Beta_trans (stern rake)

            _logger.LogDebug(
                "[SHIPD_ADAPTER] Scaled beam-related angles for beam change {Old}m → {New}m: Beta={Beta}, Beta_trans={BetaTrans}",
                oldBeam, newBeam, adjusted[8], adjusted[27]);
        }

        // Scale draft-related parameters
        var draftRatio = newDraft / oldDraft;
        if (Math.Abs(draftRatio - 1.0m) > 0.05m)
        {
            // Adjust deadrise to maintain form
            adjusted[19] *= (decimal)Math.Pow((double)(oldDraft / newDraft), 0.3); // Cdrft (deadrise)

            _logger.LogDebug(
                "[SHIPD_ADAPTER] Scaled draft-related parameters for draft change {Old}m → {New}m: Cdrft={Cdrft}",
                oldDraft, newDraft, adjusted[19]);
        }

        // Clamp all values to valid metadata ranges
        for (int i = 0; i < adjusted.Length; i++)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == i);
            if (param != null)
            {
                if (param.Min.HasValue) adjusted[i] = Math.Max(param.Min.Value, adjusted[i]);
                if (param.Max.HasValue) adjusted[i] = Math.Min(param.Max.Value, adjusted[i]);
            }
        }

        return adjusted;
    }

    /// <summary>
    /// Adjusts ShipD vector when form coefficients change.
    /// Modifies hull form parameters to achieve the target coefficient while maintaining design character.
    /// </summary>
    public decimal[] AdjustVectorForCoefficientChange(
        decimal[] originalVector,
        string coefficient,
        decimal oldValue,
        decimal newValue,
        IReadOnlyList<ShipDParameterMetadataDto> metadata)
    {
        var adjusted = (decimal[])originalVector.Clone();
        var ratio = newValue / oldValue;

        if (coefficient == "Cb")
        {
            // Adjust section fullness parameters
            // Higher Cb = fuller sections
            adjusted[9] *= ratio;   // Rc (bow curvature)
            adjusted[29] *= ratio;  // Rc_trans (stern curvature)

            // For significant Cb increases, also adjust midship features
            if (ratio > 1.05m)
            {
                // Increase fullness: enhance sheer, reduce tumblehome
                adjusted[20] = Math.Min(1.0m, adjusted[20] * 1.1m); // bit_EP_S (sheer)
                adjusted[21] = Math.Max(0.0m, adjusted[21] * 0.9m); // bit_EP_T (tumblehome)
            }

            _logger.LogDebug(
                "[SHIPD_ADAPTER] Adjusted Cb {Old} → {New}: Rc={Rc}, Rc_trans={RcTrans}",
                oldValue, newValue, adjusted[9], adjusted[29]);
        }
        else if (coefficient == "Cp")
        {
            // Adjust longitudinal distribution
            // Higher Cp = more parallel body (shorter bow/stern)
            var lmAdjust = (ratio - 1.0m) * 0.2m;
            adjusted[1] = Math.Max(0.05m, adjusted[1] - lmAdjust / 2); // Reduce Lb
            adjusted[2] = Math.Max(0.05m, adjusted[2] - lmAdjust / 2); // Reduce Ls

            _logger.LogDebug(
                "[SHIPD_ADAPTER] Adjusted Cp {Old} → {New}: Lb={Lb}, Ls={Ls}",
                oldValue, newValue, adjusted[1], adjusted[2]);
        }
        else if (coefficient == "Cwp")
        {
            // Adjust waterplane shape
            // Higher Cwp = wider waterplane at ends
            adjusted[8] *= ratio;   // Beta (flare)
            adjusted[27] *= ratio;  // Beta_trans (stern rake)

            _logger.LogDebug(
                "[SHIPD_ADAPTER] Adjusted Cwp {Old} → {New}: Beta={Beta}, Beta_trans={BetaTrans}",
                oldValue, newValue, adjusted[8], adjusted[27]);
        }

        // Validate Lb + Ls < 1.0
        if (adjusted[1] + adjusted[2] >= 1.0m)
        {
            var excess = adjusted[1] + adjusted[2] - 0.95m;
            adjusted[1] = Math.Max(0.05m, adjusted[1] - excess / 2);
            adjusted[2] = Math.Max(0.05m, adjusted[2] - excess / 2);
            _logger.LogWarning(
                "[SHIPD_ADAPTER] Clamped Lb+Ls to ensure Lm > 0: Lb={Lb}, Ls={Ls}",
                adjusted[1], adjusted[2]);
        }

        // Clamp all values to valid metadata ranges
        for (int i = 0; i < adjusted.Length; i++)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == i);
            if (param != null)
            {
                if (param.Min.HasValue) adjusted[i] = Math.Max(param.Min.Value, adjusted[i]);
                if (param.Max.HasValue) adjusted[i] = Math.Min(param.Max.Value, adjusted[i]);
            }
        }

        return adjusted;
    }

    /// <summary>
    /// Updates a single ShipD parameter in the vector (for direct parameter adjustments).
    /// Normalizes incoming denormalized values (e.g., degrees for angles) to 0-1 range.
    /// Ratio parameters are already in 0-1 range and used as-is.
    /// </summary>
    public decimal[] UpdateShipDParameter(
        decimal[] originalVector,
        int parameterIndex,
        decimal newValue,
        IReadOnlyList<ShipDParameterMetadataDto> metadata)
    {
        var adjusted = (decimal[])originalVector.Clone();

        if (parameterIndex < 0 || parameterIndex >= adjusted.Length)
        {
            throw new ArgumentOutOfRangeException(nameof(parameterIndex), $"Parameter index must be between 0 and {adjusted.Length - 1}");
        }

        var param = metadata.FirstOrDefault(m => m.ParameterIndex == parameterIndex);
        decimal normalizedValue = newValue;

        // Parameters that are ratios (0-1 range) - use value as-is
        var ratioParameters = new HashSet<int> { 1, 2, 9, 10, 14, 22, 24, 28, 29, 30, 33, 34, 35, 36, 37 };
        // Boolean parameters (0 or 1)
        var booleanParameters = new HashSet<int> { 20, 21, 31 };

        if (ratioParameters.Contains(parameterIndex))
        {
            // Ratio parameters are already in 0-1 range - use as-is
            normalizedValue = newValue;
            _logger.LogDebug(
                "[SHIPD_ADAPTER] Using ratio parameter[{Index}] value as-is: {Value}",
                parameterIndex, normalizedValue);
        }
        else if (booleanParameters.Contains(parameterIndex))
        {
            // Boolean parameters: convert to 0 or 1
            normalizedValue = newValue > 0.5m ? 1m : 0m;
            _logger.LogDebug(
                "[SHIPD_ADAPTER] Converted boolean parameter[{Index}]: {Value} -> {Normalized}",
                parameterIndex, newValue, normalizedValue);
        }
        else if (param != null && param.Min.HasValue && param.Max.HasValue)
        {
            // Physical parameters (angles, etc.) - normalize from physical units to 0-1 range
            var range = param.Max.Value - param.Min.Value;

            // Check if this is a physical parameter (min < 0 or max > 1) or value is outside [0, 1]
            bool isPhysicalParameter = param.Min.Value < 0m || param.Max.Value > 1m;
            bool valueOutsideNormalizedRange = newValue < 0m || newValue > 1m;

            if (range > 0m && (isPhysicalParameter || valueOutsideNormalizedRange))
            {
                // Value is denormalized (e.g., 15 degrees) - normalize it to 0-1 range
                normalizedValue = (newValue - param.Min.Value) / range;
                normalizedValue = Math.Max(0m, Math.Min(1m, normalizedValue)); // Clamp to [0, 1]
                _logger.LogDebug(
                    "[SHIPD_ADAPTER] Normalized physical parameter[{Index}]: {Value} ({Unit}) -> {Normalized} (0-1 range) using range [{Min}, {Max}]",
                    parameterIndex, newValue, param.Unit ?? "unit", normalizedValue, param.Min.Value, param.Max.Value);
            }
            else
            {
                // Value appears to already be normalized (0-1 range) or metadata suggests normalized
                normalizedValue = Math.Max(0m, Math.Min(1m, newValue));
                _logger.LogDebug(
                    "[SHIPD_ADAPTER] Parameter[{Index}] value appears normalized, using as-is: {Value}",
                    parameterIndex, normalizedValue);
            }
        }
        else
        {
            // No metadata available - assume value is already normalized (0-1 range)
            normalizedValue = Math.Max(0m, Math.Min(1m, newValue));
            _logger.LogWarning(
                "[SHIPD_ADAPTER] No metadata for parameter[{Index}], assuming normalized value: {Value}",
                parameterIndex, normalizedValue);
        }

        // Apply normalized value
        adjusted[parameterIndex] = normalizedValue;

        // Clamp to valid range (should already be in range, but double-check)
        if (param != null)
        {
            if (param.Min.HasValue) adjusted[parameterIndex] = Math.Max(0m, adjusted[parameterIndex]); // ShipD vector uses 0-1 range
            if (param.Max.HasValue) adjusted[parameterIndex] = Math.Min(1m, adjusted[parameterIndex]); // ShipD vector uses 0-1 range
        }

        // Special validation for longitudinal proportions (Lb + Ls < 1.0)
        if (parameterIndex == 1 || parameterIndex == 2) // Lb or Ls
        {
            if (adjusted[1] + adjusted[2] >= 1.0m)
            {
                var excess = adjusted[1] + adjusted[2] - 0.95m;
                if (parameterIndex == 1) // Adjusting Lb
                {
                    adjusted[1] = Math.Max(0.05m, adjusted[1] - excess);
                }
                else // Adjusting Ls
                {
                    adjusted[2] = Math.Max(0.05m, adjusted[2] - excess);
                }
                _logger.LogWarning(
                    "[SHIPD_ADAPTER] Clamped parameter {Index} to ensure Lb+Ls < 1.0: Lb={Lb}, Ls={Ls}",
                    parameterIndex, adjusted[1], adjusted[2]);
            }
        }

        _logger.LogDebug(
            "[SHIPD_ADAPTER] Updated ShipD parameter[{Index}] = {Value}",
            parameterIndex, adjusted[parameterIndex]);

        return adjusted;
    }

    /// <summary>
    /// Ensures bulb dimensions (Lbb, Hbb, Bbb) are set to sensible defaults when bulb is enabled.
    /// This prevents the issue where bulb is enabled but dimensions are zero or minimal, resulting in no effective bulb geometry.
    /// </summary>
    /// <param name="vector">ShipD parameter vector</param>
    /// <param name="metadata">Parameter metadata</param>
    private void EnsureSensibleBulbDimensions(
        decimal[] vector,
        IReadOnlyList<ShipDParameterMetadataDto> metadata)
    {
        // Only apply if bulb is enabled
        if (vector[31] <= 0.5m) // bit_BB
        {
            return;
        }

        const decimal minLbbThreshold = 0.01m; // 1% of Lpp (very small, should be at least 15%)
        const decimal minHbbThreshold = 0.05m; // 5% of draft (very small, should be at least 20%)
        const decimal minBbbThreshold = 0.05m; // 5% of beam (very small, should be at least 20%)

        // Sensible defaults based on recommendations:
        // - Lbb: 15% of Lpp (normalized: 0.15)
        // - Hbb: 20% of draft (normalized: 0.2)
        // - Bbb: 25% of beam (normalized: 0.25)
        const decimal defaultLbb = 0.15m; // 15% of Lpp
        const decimal defaultHbb = 0.2m;  // 20% of draft
        const decimal defaultBbb = 0.25m; // 25% of beam

        bool updated = false;

        // Check and set Lbb (Bulb length ratio, index 33)
        if (vector[33] < minLbbThreshold)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == 33);
            if (param != null)
            {
                var oldValue = vector[33];
                var clampedValue = Math.Clamp(defaultLbb, param.Min ?? 0m, param.Max ?? 0.2m);
                if (oldValue != clampedValue)
                {
                    vector[33] = clampedValue;
                    updated = true;
                    _logger.LogInformation(
                        "[SHIPD_ADAPTER] Set Lbb to sensible default: {Value} (was {OldValue}, recommended: 15% of Lpp)",
                        clampedValue, oldValue);
                }
            }
        }

        // Check and set Hbb (Bulb height ratio, index 34)
        if (vector[34] < minHbbThreshold)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == 34);
            if (param != null)
            {
                var oldValue = vector[34];
                var clampedValue = Math.Clamp(defaultHbb, param.Min ?? 0m, param.Max ?? 1m);
                if (oldValue != clampedValue)
                {
                    vector[34] = clampedValue;
                    updated = true;
                    _logger.LogInformation(
                        "[SHIPD_ADAPTER] Set Hbb to sensible default: {Value} (was {OldValue}, recommended: 20% of draft)",
                        clampedValue, oldValue);
                }
            }
        }

        // Check and set Bbb (Bulb width ratio, index 35)
        if (vector[35] < minBbbThreshold)
        {
            var param = metadata.FirstOrDefault(m => m.ParameterIndex == 35);
            if (param != null)
            {
                var oldValue = vector[35];
                var clampedValue = Math.Clamp(defaultBbb, param.Min ?? 0m, param.Max ?? 1m);
                if (oldValue != clampedValue)
                {
                    vector[35] = clampedValue;
                    updated = true;
                    _logger.LogInformation(
                        "[SHIPD_ADAPTER] Set Bbb to sensible default: {Value} (was {OldValue}, recommended: 25% of beam)",
                        clampedValue, oldValue);
                }
            }
        }

        if (updated)
        {
            _logger.LogWarning(
                "[SHIPD_ADAPTER] ✅ Applied sensible bulb dimension defaults: Lbb={Lbb}, Hbb={Hbb}, Bbb={Bbb}",
                vector[33], vector[34], vector[35]);
        }
    }

    /// <summary>
    /// Apply hardcoded bow family defaults when taxonomy doesn't provide them.
    /// This ensures different bow families produce visually distinct hull shapes.
    /// </summary>
    private void ApplyHardcodedBowFamilyDefaults(decimal[] vector, string? bowFamily, IReadOnlyList<ShipDParameterMetadataDto> metadata)
    {
        if (string.IsNullOrEmpty(bowFamily)) return;

        switch (bowFamily.ToLowerInvariant())
        {
            case "bulbous_bow":
                // Set bulb geometry based on ShipD sample data + Schneekluth standards
                // Research: temp/HULL_FAMILY_PARAMETERS_RESEARCH.md
                if (vector[31] == 0) vector[31] = 1m;    // bit_BB: 1 = bulb present
                if (vector[33] == 0) vector[33] = 0.04m; // Lbb: 4% of Lpp (data-driven: median 2.15%, Schneekluth 3-7%)
                if (vector[34] == 0) vector[34] = 0.65m; // Hbb: 65% of draft (conservative, typical practice)
                if (vector[35] == 0) vector[35] = 0.60m; // Bbb: 60% of beam (full-form typical, data mean 28%)
                _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied data-driven bulbous_bow defaults: bit_BB={BitBB}, Lbb={Lbb}%, Hbb={Hbb}%, Bbb={Bbb}%",
                    vector[31], vector[33] * 100, vector[34] * 100, vector[35] * 100);
                break;

            case "straight_raked":
            case "fine_entry":
            case "axe_bow":
            case "no_bulb":
                // CRITICAL: Explicitly set ALL bulb parameters to ZERO (no bulb)
                // This prevents EnsureSensibleBulbDimensions from adding defaults
                vector[31] = 0m; // bit_BB: 0 = no bulb
                vector[33] = 0m; // Lbb
                vector[34] = 0m; // Hbb
                vector[35] = 0m; // Bbb
                vector[36] = 0m; // Lbbm
                vector[37] = 0m; // Rbb
                _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied {BowFamily} - all bulb parameters forced to ZERO (no bulb)", bowFamily);
                break;

            default:
                _logger.LogWarning("[SHIPD_ADAPTER] ⚠️ Unknown bow family '{BowFamily}' - no defaults applied", bowFamily);
                break;
        }
    }

    /// <summary>
    /// Apply hardcoded stern family defaults when taxonomy doesn't provide them.
    /// </summary>
    private void ApplyHardcodedSternFamilyDefaults(decimal[] vector, string? sternFamily, IReadOnlyList<ShipDParameterMetadataDto> metadata)
    {
        if (string.IsNullOrEmpty(sternFamily)) return;

        switch (sternFamily.ToLowerInvariant())
        {
            case "transom_stern":
                // Data-driven values from Watson (typical cargo vessel)
                // Research: temp/HULL_FAMILY_PARAMETERS_RESEARCH.md
                if (vector[22] == 0) vector[22] = 0.08m;  // Atrans: 8% transom area ratio
                if (vector[27] == 0) vector[27] = 0.08m;  // Beta_trans: ~4.6° rake (0.08 rad)
                if (vector[29] == 0) vector[29] = 0.05m;  // Rc_trans: minimal curvature (hard knuckle)
                _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied data-driven transom_stern defaults: Atrans={Atrans}%, Beta_trans={BetaTrans}rad, Rc={Rc}",
                    vector[22] * 100, vector[27], vector[29]);
                break;

            case "cruiser_stern":
                // Rounded stern with moderate curvature
                // Research: temp/HULL_FAMILY_PARAMETERS_RESEARCH.md
                if (vector[22] == 0) vector[22] = 0m;    // Atrans: 0 = no transom
                if (vector[27] == 0) vector[27] = 0m;    // Beta_trans: 0 = no rake (rounded)
                if (vector[29] == 0) vector[29] = 0.50m; // Rc_trans: moderate curvature
                _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied data-driven cruiser_stern defaults: Rc_trans={Rc}",
                    vector[29]);
                break;

            case "canoe_stern":
                // Highly rounded stern (yacht-like)
                // Research: temp/HULL_FAMILY_PARAMETERS_RESEARCH.md
                if (vector[22] == 0) vector[22] = 0m;    // Atrans: 0 = no transom
                if (vector[27] == 0) vector[27] = 0m;    // Beta_trans: 0 = no rake
                if (vector[29] == 0) vector[29] = 0.80m; // Rc_trans: high curvature (very rounded)
                _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied data-driven canoe_stern defaults: Rc_trans={Rc}",
                    vector[29]);
                break;

            default:
                _logger.LogWarning("[SHIPD_ADAPTER] ⚠️ Unknown stern family '{SternFamily}' - no defaults applied", sternFamily);
                break;
        }
    }

    /// <summary>
    /// Apply hardcoded midship family defaults when taxonomy doesn't provide them.
    /// </summary>
    private void ApplyHardcodedMidshipFamilyDefaults(decimal[] vector, string? midshipFamily, IReadOnlyList<ShipDParameterMetadataDto> metadata)
    {
        if (string.IsNullOrEmpty(midshipFamily)) return;

        switch (midshipFamily.ToLowerInvariant())
        {
            case "full_midship":
                // Use defaults (most common for tankers/bulkers)
                // No overrides needed - baseline configuration
                _logger.LogDebug("[SHIPD_ADAPTER] Using full_midship (baseline defaults)");
                break;

            case "fine_midship":
                // Data-driven values for finer sections (higher speed vessels)
                // Research: temp/HULL_FAMILY_PARAMETERS_RESEARCH.md
                if (vector[9] == 0) vector[9] = 0.25m;   // Rc: 0.25 chine radius (softer bilge)
                if (vector[21] == 0) vector[21] = 1m;    // bit_EP_T: 1 = enable tumblehome
                _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied data-driven fine_midship defaults: Rc={Rc}, tumblehome={Tumble}",
                    vector[9], vector[21]);
                break;

            case "barge_type":
                // Data-driven values for hard chine sections
                // Research: temp/HULL_FAMILY_PARAMETERS_RESEARCH.md
                if (vector[9] == 0) vector[9] = 0.02m;   // Rc: 0.02 = very hard chine
                if (vector[10] == 0) vector[10] = 0.02m; // Rk: 0.02 = very hard knuckle
                _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied data-driven barge_type defaults: Rc={Rc}, Rk={Rk}",
                    vector[9], vector[10]);
                break;

            case "deep_v":
                // Data-driven values for planning hull deadrise
                // Research: temp/HULL_FAMILY_PARAMETERS_RESEARCH.md
                if (vector[19] == 0) vector[19] = 0.35m; // Cdrft: 0.35 deadrise coefficient (~20° at transom)
                _logger.LogInformation("[SHIPD_ADAPTER] ✅ Applied data-driven deep_v defaults: Cdrft={Cdrft}",
                    vector[19]);
                break;

            default:
                _logger.LogWarning("[SHIPD_ADAPTER] ⚠️ Unknown midship family '{MidshipFamily}' - no defaults applied", midshipFamily);
                break;
        }
    }
}
