using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using HullSizingService.Services.Integration;
using Shared.DTOs.Sizing;
using Shared.Models.Sizing;

namespace HullSizingService.Services.ShipD;

/// <summary>
/// Temporary adapter that maps mission cases to ShipD parameter vectors.
/// This implementation uses placeholder logic until full ShipD metadata ingestion is completed.
/// </summary>
public class ShipDParameterAdapter : IShipDParameterAdapter
{
    private const int ShipDParameterCount = 45;

    private readonly ILogger<ShipDParameterAdapter> _logger;
    private readonly IDataServiceClient _dataServiceClient;

    public ShipDParameterAdapter(
        ILogger<ShipDParameterAdapter> logger,
        IDataServiceClient dataServiceClient)
    {
        _logger = logger;
        _dataServiceClient = dataServiceClient;
    }

    public async Task<ShipDParameterizationResult> BuildAsync(
        MissionCase missionCase,
        CreateSizingRunDto runRequest,
        CancellationToken cancellationToken = default)
    {
        // Fetch metadata (best-effort; fall back to local defaults if unavailable)
        var parameterMetadataTask = _dataServiceClient.GetShipDParameterMetadataAsync(cancellationToken);
        var taxonomyTask = _dataServiceClient.GetShipDVesselTaxonomyAsync(cancellationToken);
        await Task.WhenAll(parameterMetadataTask, taxonomyTask);

        var parameterMetadata = parameterMetadataTask.Result;
        var taxonomy = taxonomyTask.Result;

        // Use incoming selections when available; otherwise fall back to mission defaults.
        var vesselCategory = (runRequest.VesselCategory ?? missionCase.MissionCategory ?? "commercial").ToLowerInvariant();
        var vesselType = (runRequest.VesselType ?? missionCase.MissionType).ToLowerInvariant();
        var bowFamily = runRequest.BowFamily ?? missionCase.BowFamily;
        var midshipFamily = runRequest.MidshipFamily ?? missionCase.MidshipFamily;
        var sternFamily = runRequest.SternFamily ?? missionCase.SternFamily;
        var maskVersion = runRequest.FamilyMaskVersion ?? missionCase.FamilyMaskVersion ?? 1;

        var taxonomyEntry = taxonomy.FirstOrDefault(t =>
            string.Equals(t.Category, vesselCategory, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(t.Type, vesselType, StringComparison.OrdinalIgnoreCase));

        // Placeholder vector: start with zeros and inject a few normalized mission hints.
        var vector = Enumerable.Repeat(0m, ShipDParameterCount).ToArray();
        var warnings = new List<string>();

        if (!string.IsNullOrWhiteSpace(runRequest.ShipdInputVectorJson))
        {
            try
            {
                var overrideVector = JsonSerializer.Deserialize<List<decimal>>(runRequest.ShipdInputVectorJson);
                if (overrideVector != null && overrideVector.Count == ShipDParameterCount)
                {
                    vector = overrideVector.ToArray();
                }
                else
                {
                    warnings.Add("Provided ShipD input vector did not contain 45 entries; using autogenerated defaults.");
                }
            }
            catch (JsonException ex)
            {
                warnings.Add("Provided ShipD input vector could not be parsed; using autogenerated defaults.");
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Failed to parse user-supplied ShipD vector. Falling back to autogenerated defaults.");
            }
        }
        if (missionCase.CapLoaM.HasValue && missionCase.CapLoaM.Value > 0)
        {
            vector[0] = Math.Clamp(missionCase.CapLoaM.Value / 300m, 0.0m, 1.0m);
        }

        if (missionCase.CapBeamM.HasValue && missionCase.CapBeamM.Value > 0)
        {
            vector[7] = Math.Clamp(missionCase.CapBeamM.Value / 50m, 0.0m, 1.0m);
        }

        if (missionCase.ServiceSpeedKn > 0)
        {
            vector[20] = Math.Clamp(missionCase.ServiceSpeedKn / 40m, 0.0m, 1.0m);
        }

        // Apply taxonomy defaults when available
        if (taxonomyEntry != null)
        {
            if (bowFamily == null && taxonomyEntry.BowFamilies.Count > 0)
            {
                bowFamily = taxonomyEntry.BowFamilies.First();
                warnings.Add($"Bow family defaulted to '{bowFamily}' from taxonomy.");
            }

            if (midshipFamily == null && taxonomyEntry.MidshipFamilies.Count > 0)
            {
                midshipFamily = taxonomyEntry.MidshipFamilies.First();
                warnings.Add($"Midship family defaulted to '{midshipFamily}' from taxonomy.");
            }

            if (sternFamily == null && taxonomyEntry.SternFamilies.Count > 0)
            {
                sternFamily = taxonomyEntry.SternFamilies.First();
                warnings.Add($"Stern family defaulted to '{sternFamily}' from taxonomy.");
            }
        }
        else
        {
            warnings.Add($"No taxonomy entry found for category '{vesselCategory}' and type '{vesselType}'.");
        }

        if (bowFamily is null || midshipFamily is null || sternFamily is null)
        {
            warnings.Add("One or more hull families were not specified; using defaults during ShipD processing.");
        }

        IDictionary<string, object>? additional = null;
        if (runRequest.Options?.AdditionalParameters != null && runRequest.Options.AdditionalParameters.Count > 0)
        {
            additional = runRequest.Options.AdditionalParameters;
        }

        if (!string.IsNullOrWhiteSpace(taxonomyEntry?.AdditionalParametersJson))
        {
            try
            {
                var taxonomyParams = JsonSerializer.Deserialize<Dictionary<string, object>>(taxonomyEntry.AdditionalParametersJson);
                if (taxonomyParams != null)
                {
                    additional ??= new Dictionary<string, object>();
                    foreach (var pair in taxonomyParams)
                    {
                        additional[pair.Key] = pair.Value;
                    }
                }
            }
            catch (JsonException ex)
            {
                warnings.Add("Failed to parse additional taxonomy parameters.");
                _logger.LogWarning(ex, "[SHIPD_ADAPTER] Could not parse AdditionalParametersJson for taxonomy entry {Category}/{Type}", vesselCategory, vesselType);
            }
        }

        var labels = parameterMetadata.Count == ShipDParameterCount
            ? parameterMetadata
                .OrderBy(p => p.ParameterIndex)
                .Select(p => p.Label)
                .ToArray()
            : Enumerable.Range(0, ShipDParameterCount)
                .Select(i => $"param_{i:00}")
                .ToArray();

        _logger.LogDebug(
            "[SHIPD_ADAPTER] Generated ShipD vector (maskVersion={MaskVersion}) for category={Category}, type={Type}, bow={Bow}, mid={Mid}, stern={Stern}. Payload={Payload}",
            maskVersion,
            vesselCategory,
            vesselType,
            bowFamily,
            midshipFamily,
            sternFamily,
            JsonSerializer.Serialize(vector));

        var result = new ShipDParameterizationResult(
            ParameterVector: vector,
            ParameterLabels: labels,
            VesselCategory: vesselCategory,
            VesselType: vesselType,
            BowFamily: bowFamily,
            MidshipFamily: midshipFamily,
            SternFamily: sternFamily,
            MaskVersion: maskVersion,
            AdditionalParameters: additional,
            Warnings: warnings);

        return result;
    }
}
