/**
 * ShipD Geometry Generator for Frontend Visualization
 *
 * Converts ShipD parameter vectors and geometry data from backend into Three.js geometry
 * for 3D visualization. Uses geometry generated by backend ShipDHullGeometryService when available,
 * or generates geometry directly from ShipD parameters.
 *
 * @module shipdGeometryGenerator
 */

import * as THREE from "three";
import type { ShipDParameterMetadata } from "../types/sizing";

// ============================================================================
// TYPES & INTERFACES
// ============================================================================

/**
 * Hull station (transverse section) from ShipD geometry
 */
export interface ShipDHullStation {
  position: number; // 0 = aft, 1 = forward
  offsets: Record<number, number>; // height (m) -> half-breadth (m)
  hasBulb?: boolean;
  bulbOffsets?: Record<number, number>;
}

/**
 * Hull sections data from backend
 */
export interface ShipDHullSections {
  stations: ShipDHullStation[];
  stationPositions: number[];
}

/**
 * Parameters for generating ShipD hull geometry
 */
export interface ShipDGeometryParams {
  /** ShipD 45-parameter vector (normalized 0-1) */
  shipdVector: number[];
  /** Length between perpendiculars (m) */
  lppM: number;
  /** Maximum beam (m) */
  beamM: number;
  /** Design draft (m) */
  draftM: number;
  /** ShipD parameter metadata for denormalization */
  metadata: ShipDParameterMetadata[];
  /** Resolution factor (1.0 = default, higher = more detail) */
  resolution?: number;
}

// ============================================================================
// MAIN FUNCTIONS
// ============================================================================

/**
 * Generates 3D hull geometry from ShipD parameter vector or backend geometry data
 */
export function generateShipDHull3D(
  params: ShipDGeometryParams | { sections: ShipDHullSections; lppM: number }
): THREE.BufferGeometry {
  // If sections are provided (from backend), use them directly
  if ("sections" in params) {
    return generateHull3DFromSections(params.sections, params.lppM);
  }

  // Otherwise, generate from ShipD vector
  const sections = generateShipDSections(params);
  return generateHull3DFromSections(sections, params.lppM);
}

/**
 * Generates hull sections from ShipD parameter vector
 */
export function generateShipDSections(
  params: ShipDGeometryParams,
  stationCount: number = 20
): ShipDHullSections {
  const { shipdVector, lppM, beamM, draftM, metadata, resolution = 1.0 } = params;

  if (shipdVector.length !== 45) {
    throw new Error(
      `ShipD vector must contain exactly 45 parameters (received ${shipdVector.length})`
    );
  }

  // Denormalize key parameters
  const denormalized = denormalizeParameters(shipdVector, metadata);

  // LOG KEY PARAMETERS for debugging (debug level to reduce noise during optimization)
  // Note: vector[1] and vector[2] are already ratios, not denormalized
  console.debug("[ShipD Geometry] Key parameters:", {
    longitudinal: {
      bow_length: shipdVector[1]?.toFixed(2),
      stern_length: shipdVector[2]?.toFixed(2),
      mid_length: (1.0 - shipdVector[1] - shipdVector[2])?.toFixed(2),
    },
    bow: {
      flare_deg: denormalized[8]?.toFixed(1),
      curvature: denormalized[9]?.toFixed(2),
      knuckle: denormalized[10]?.toFixed(2),
      kappa_bow: denormalized[14]?.toFixed(2),
      deadrise_deg: denormalized[19]?.toFixed(1),
    },
    midship: {
      sheer_enabled: denormalized[20] > 0.5,
      tumblehome_enabled: denormalized[21] > 0.5,
    },
    stern: {
      atrans: denormalized[22]?.toFixed(2),
      kappa_stern: denormalized[24]?.toFixed(2),
      rake_deg: denormalized[27]?.toFixed(1),
      transom_width: denormalized[28]?.toFixed(2),
      curvature: denormalized[29]?.toFixed(2),
      knuckle: denormalized[30]?.toFixed(2),
    },
    bulb: {
      enabled: shipdVector[31] > 0.5,
      length: shipdVector[33]?.toFixed(2), // Ratio - use directly
      height: shipdVector[34]?.toFixed(2), // Ratio - use directly
      width: shipdVector[35]?.toFixed(2), // Ratio - use directly
      asymmetry: shipdVector[36]?.toFixed(2), // Ratio - use directly
      fillet: shipdVector[37]?.toFixed(2), // Ratio - use directly
    },
  });

  // Extract longitudinal proportions with validation and fallbacks
  // IMPORTANT: vector[1] and vector[2] are already ratios (0-1), NOT normalized values
  // They should NOT be denormalized - they ARE the actual ratios
  let lb = shipdVector[1]; // Bow length ratio (Lb from ShipD) - already a ratio
  let ls = shipdVector[2]; // Stern length ratio (Ls from ShipD) - already a ratio

  // VALIDATION: ShipD parameters should be reasonable
  // Lb and Ls are ratios of Lpp, typically 0.15-0.45 each
  const MIN_BOW_LENGTH = 0.15; // Minimum 15% for bow
  const MIN_STERN_LENGTH = 0.15; // Minimum 15% for stern
  const MAX_BOW_LENGTH = 0.45; // Maximum 45% for bow
  const MAX_STERN_LENGTH = 0.45; // Maximum 45% for stern

  // Check if values are unrealistic (missing metadata, bad data, or extreme edge cases)
  const needsFallback =
    lb == null ||
    ls == null ||
    isNaN(lb) ||
    isNaN(ls) ||
    lb < MIN_BOW_LENGTH ||
    ls < MIN_STERN_LENGTH ||
    lb > MAX_BOW_LENGTH ||
    ls > MAX_STERN_LENGTH ||
    lb + ls > 0.85; // Ensure at least 15% midship

  if (needsFallback) {
    // Debug log instead of warn - this is expected behavior during optimization
    // when parameters may temporarily be out of bounds
    console.debug(
      "[ShipD Geometry] Invalid longitudinal proportions detected, using fallback values:",
      {
        original: { lb, ls, sum: lb + ls },
        reason:
          lb == null || ls == null || isNaN(lb) || isNaN(ls)
            ? "Missing or invalid values"
            : lb < MIN_BOW_LENGTH || ls < MIN_STERN_LENGTH
              ? "Too short"
              : lb > MAX_BOW_LENGTH || ls > MAX_STERN_LENGTH
                ? "Too long"
                : lb + ls > 0.85
                  ? "Sum exceeds 85%"
                  : "Unknown",
      }
    );

    // Realistic fallback: typical container ship proportions
    lb = 0.3; // 30% bow
    ls = 0.3; // 30% stern

    // Debug log instead of regular log to reduce noise
    console.debug("[ShipD Geometry] Using fallback proportions:", {
      bow: "30%",
      midship: "40%",
      stern: "30%",
    });
  }

  const lm = 1.0 - lb - ls; // Mid-body length ratio

  // Calculate boundaries
  const bowStart = ls + lm; // Start of bow region (0 = aft)
  const midStart = ls; // Start of mid-body region

  const stations: ShipDHullStation[] = [];
  const stationPositions: number[] = [];

  const effectiveStationCount = Math.max(10, Math.round(stationCount * resolution));

  // Generate stations
  for (let i = 0; i < effectiveStationCount; i++) {
    const stationPos = i / (effectiveStationCount - 1); // 0 = aft, 1 = forward
    stationPositions.push(stationPos);

    // Determine which region this station is in
    const region = stationPos < midStart ? "stern" : stationPos < bowStart ? "midship" : "bow";

    // Generate offsets for this station
    const offsets = generateStationOffsets(
      stationPos,
      region,
      denormalized,
      lppM,
      beamM,
      draftM,
      metadata
    );

    // Check for bulb (only in bow region)
    const hasBulb = region === "bow" && shipdVector[31] > 0.5; // bit_BB
    let bulbOffsets: Record<number, number> | undefined;

    if (hasBulb) {
      bulbOffsets = generateBulbOffsets(stationPos, shipdVector, lppM, beamM, draftM);
    }

    stations.push({
      position: stationPos,
      offsets,
      hasBulb,
      bulbOffsets,
    });
  }

  return { stations, stationPositions };
}

/**
 * Generates bulb geometry from ShipD parameters
 */
export function generateShipDBulb(
  shipdVector: number[],
  _lppM: number,
  beamM: number,
  draftM: number,
  _metadata: ShipDParameterMetadata[]
): THREE.BufferGeometry | null {
  if (shipdVector.length !== 45) {
    return null;
  }

  // Check if bulb is enabled
  if (shipdVector[31] <= 0.5) {
    return null; // bit_BB
  }

  // Bulb parameters - these are ratios, use vector directly
  // const lbb = shipdVector[33]; // Bulb length ratio - not used in ellipsoid generation
  const hbb = shipdVector[34]; // Bulb height ratio
  const bbb = shipdVector[35]; // Bulb width ratio
  // const lbbm = denormalized[36]; // Bulb asymmetry - not used in simplified implementation
  // const rbb = denormalized[37]; // Bulb radius - not used in simplified implementation

  // const bulbLength = lbb * lppM; // Not used in simplified implementation
  const bulbHeight = hbb * draftM;
  const bulbWidth = bbb * beamM;

  // Generate ellipsoid geometry for bulb
  const geometry = new THREE.BufferGeometry();
  const vertices: number[] = [];
  const indices: number[] = [];

  const segments = 16;
  const rings = 8;

  // Generate vertices
  for (let ring = 0; ring <= rings; ring++) {
    const v = ring / rings;
    const y = -bulbHeight + v * bulbHeight * 2; // Vertical position

    for (let seg = 0; seg <= segments; seg++) {
      const u = seg / segments;
      const theta = u * Math.PI * 2;

      // Ellipsoid shape
      const radius = (bulbWidth / 2) * Math.sqrt(1 - Math.pow(y / bulbHeight, 2));
      const x = Math.cos(theta) * radius;
      const z = Math.sin(theta) * radius;

      vertices.push(x, y, z);
    }
  }

  // Generate faces
  for (let ring = 0; ring < rings; ring++) {
    for (let seg = 0; seg < segments; seg++) {
      const a = ring * (segments + 1) + seg;
      const b = ring * (segments + 1) + seg + 1;
      const c = (ring + 1) * (segments + 1) + seg;
      const d = (ring + 1) * (segments + 1) + seg + 1;

      indices.push(a, b, c);
      indices.push(b, d, c);
    }
  }

  geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertices, 3));
  geometry.setIndex(indices);
  geometry.computeVertexNormals();

  return geometry;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Generates 3D geometry from hull sections
 */
function generateHull3DFromSections(
  sections: ShipDHullSections,
  lppM: number
): THREE.BufferGeometry {
  const geometry = new THREE.BufferGeometry();
  const vertices: number[] = [];
  const indices: number[] = [];
  const normals: number[] = [];

  let vertexIndex = 0;
  const vertexMap = new Map<string, number>(); // (station, height) -> vertex index

  // First pass: create vertices
  // Three.js coordinate system: X = right/left (starboard/port), Y = up/down (height), Z = forward/back (longitudinal)
  // Center hull at origin: longitudinal from -lpp/2 (aft) to +lpp/2 (forward)
  for (const station of sections.stations) {
    // Convert station position (0=aft, 1=forward) to centered Z coordinate
    // 0 -> -lpp/2 (aft), 1 -> +lpp/2 (forward)
    const z = (station.position - 0.5) * lppM; // Center at origin

    // Sort heights for consistent ordering
    const heights = Object.keys(station.offsets)
      .map(Number)
      .sort((a, b) => a - b);

    for (const height of heights) {
      const halfBreadth = station.offsets[height];

      // At keel (height=0), port and starboard share the same vertex (half-breadth=0)
      if (height === 0 || halfBreadth === 0) {
        const keyKeel = `${station.position}-${height}-keel`;
        if (!vertexMap.has(keyKeel)) {
          vertices.push(0, height, z); // X=0 (centerline), Y=height, Z=longitudinal
          normals.push(0, 1, 0); // Normal pointing up (will be recomputed)
          const keelIndex = vertexIndex++;
          vertexMap.set(keyKeel, keelIndex);
          // Both port and starboard reference the same keel vertex
          vertexMap.set(`${station.position}-${height}-port`, keelIndex);
          vertexMap.set(`${station.position}-${height}-starboard`, keelIndex);
        }
      } else {
        // Port side (negative X)
        const keyPort = `${station.position}-${height}-port`;
        if (!vertexMap.has(keyPort)) {
          vertices.push(-halfBreadth, height, z); // X=port, Y=height, Z=longitudinal
          normals.push(-1, 0, 0); // Normal pointing port (will be recomputed)
          vertexMap.set(keyPort, vertexIndex++);
        }

        // Starboard side (positive X)
        const keyStarboard = `${station.position}-${height}-starboard`;
        if (!vertexMap.has(keyStarboard)) {
          vertices.push(halfBreadth, height, z); // X=starboard, Y=height, Z=longitudinal
          normals.push(1, 0, 0); // Normal pointing starboard (will be recomputed)
          vertexMap.set(keyStarboard, vertexIndex++);
        }
      }
    }

    // Add bulb vertices if present
    if (station.hasBulb && station.bulbOffsets) {
      const bulbHeights = Object.keys(station.bulbOffsets)
        .map(Number)
        .sort((a, b) => a - b);

      for (const height of bulbHeights) {
        const halfBreadth = station.bulbOffsets[height];

        const keyBulbPort = `${station.position}-${height}-bulb-port`;
        if (!vertexMap.has(keyBulbPort)) {
          vertices.push(-halfBreadth, height, z);
          normals.push(-1, 0, 0);
          vertexMap.set(keyBulbPort, vertexIndex++);
        }

        const keyBulbStarboard = `${station.position}-${height}-bulb-starboard`;
        if (!vertexMap.has(keyBulbStarboard)) {
          vertices.push(halfBreadth, height, z);
          normals.push(1, 0, 0);
          vertexMap.set(keyBulbStarboard, vertexIndex++);
        }
      }
    }
  }

  // Second pass: create faces (connect adjacent stations and heights)
  for (let i = 0; i < sections.stations.length - 1; i++) {
    const station1 = sections.stations[i];
    const station2 = sections.stations[i + 1];

    const heights1 = Object.keys(station1.offsets)
      .map(Number)
      .sort((a, b) => a - b);
    const heights2 = Object.keys(station2.offsets)
      .map(Number)
      .sort((a, b) => a - b);

    // Match heights (interpolate if needed)
    const allHeights = Array.from(new Set([...heights1, ...heights2])).sort((a, b) => a - b);

    for (let h = 0; h < allHeights.length - 1; h++) {
      const h1 = allHeights[h];
      const h2 = allHeights[h + 1];

      // Note: Half-breadths are not used in simplified mesh generation
      // The mesh is generated directly from vertex positions stored in vertexMap

      // Create quad (two triangles) for port side
      const v1_port = vertexMap.get(`${station1.position}-${h1}-port`);
      const v2_port = vertexMap.get(`${station1.position}-${h2}-port`);
      const v3_port = vertexMap.get(`${station2.position}-${h1}-port`);
      const v4_port = vertexMap.get(`${station2.position}-${h2}-port`);

      if (
        v1_port !== undefined &&
        v2_port !== undefined &&
        v3_port !== undefined &&
        v4_port !== undefined
      ) {
        indices.push(v1_port, v2_port, v3_port);
        indices.push(v2_port, v4_port, v3_port);
      }

      // Create quad for starboard side
      const v1_starboard = vertexMap.get(`${station1.position}-${h1}-starboard`);
      const v2_starboard = vertexMap.get(`${station1.position}-${h2}-starboard`);
      const v3_starboard = vertexMap.get(`${station2.position}-${h1}-starboard`);
      const v4_starboard = vertexMap.get(`${station2.position}-${h2}-starboard`);

      if (
        v1_starboard !== undefined &&
        v2_starboard !== undefined &&
        v3_starboard !== undefined &&
        v4_starboard !== undefined
      ) {
        indices.push(v1_starboard, v3_starboard, v2_starboard);
        indices.push(v2_starboard, v3_starboard, v4_starboard);
      }
    }
  }

  // Add closing faces at bow (position = 1, forward end)
  const bowStation = sections.stations.find((s) => Math.abs(s.position - 1.0) < 0.01);
  if (bowStation) {
    const bowHeights = Object.keys(bowStation.offsets)
      .map(Number)
      .sort((a, b) => a - b);

    // Close bow end (connect all points at bow station)
    for (let h = 0; h < bowHeights.length - 1; h++) {
      const h1 = bowHeights[h];
      const h2 = bowHeights[h + 1];

      const v1_port = vertexMap.get(`${bowStation.position}-${h1}-port`);
      const v2_port = vertexMap.get(`${bowStation.position}-${h2}-port`);
      const v1_starboard = vertexMap.get(`${bowStation.position}-${h1}-starboard`);
      const v2_starboard = vertexMap.get(`${bowStation.position}-${h2}-starboard`);

      // Create triangle closing the bow (port and starboard meet at centerline)
      if (
        v1_port !== undefined &&
        v2_port !== undefined &&
        v1_starboard !== undefined &&
        v2_starboard !== undefined
      ) {
        // Bow closing face (two triangles forming a quad)
        indices.push(v1_port, v1_starboard, v2_port);
        indices.push(v2_port, v1_starboard, v2_starboard);
      }
    }
  }

  // Add closing faces at stern (position = 0, aft end)
  const sternStation = sections.stations.find((s) => Math.abs(s.position - 0.0) < 0.01);
  if (sternStation) {
    const sternHeights = Object.keys(sternStation.offsets)
      .map(Number)
      .sort((a, b) => a - b);

    // Close stern end (connect all points at stern station)
    for (let h = 0; h < sternHeights.length - 1; h++) {
      const h1 = sternHeights[h];
      const h2 = sternHeights[h + 1];

      const v1_port = vertexMap.get(`${sternStation.position}-${h1}-port`);
      const v2_port = vertexMap.get(`${sternStation.position}-${h2}-port`);
      const v1_starboard = vertexMap.get(`${sternStation.position}-${h1}-starboard`);
      const v2_starboard = vertexMap.get(`${sternStation.position}-${h2}-starboard`);

      // Create triangle closing the stern (port and starboard meet at centerline)
      if (
        v1_port !== undefined &&
        v2_port !== undefined &&
        v1_starboard !== undefined &&
        v2_starboard !== undefined
      ) {
        // Stern closing face (two triangles forming a quad)
        indices.push(v1_starboard, v1_port, v2_starboard);
        indices.push(v2_starboard, v1_port, v2_port);
      }
    }
  }

  // Add bottom closing face (keel) - connect all stations at height=0
  // At keel (height=0), port and starboard share the same vertex (half-breadth=0)
  const keelVertices: number[] = [];
  for (const station of sections.stations) {
    // At height=0, both port and starboard reference the same keel vertex
    const keelVertex =
      vertexMap.get(`${station.position}-0-keel`) ||
      vertexMap.get(`${station.position}-0-port`) ||
      vertexMap.get(`${station.position}-0-starboard`);
    if (keelVertex !== undefined && !keelVertices.includes(keelVertex)) {
      keelVertices.push(keelVertex);
    }
  }

  // Create bottom face by connecting keel vertices along the longitudinal axis
  if (keelVertices.length >= 3) {
    // Sort by Z coordinate (longitudinal position: aft to forward)
    const sortedKeelVertices = keelVertices.sort((a, b) => {
      const za = vertices[a * 3 + 2]; // Z coordinate (longitudinal)
      const zb = vertices[b * 3 + 2];
      return za - zb;
    });

    // Create triangles along the keel (forming a continuous bottom surface)
    for (let i = 0; i < sortedKeelVertices.length - 2; i++) {
      indices.push(sortedKeelVertices[i], sortedKeelVertices[i + 1], sortedKeelVertices[i + 2]);
    }
  }

  geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertices, 3));
  geometry.setAttribute("normal", new THREE.Float32BufferAttribute(normals, 3));
  geometry.setIndex(indices);
  geometry.computeVertexNormals();

  return geometry;
}

// Note: getHalfBreadthAtHeight function removed - not used in simplified mesh generation
// Can be re-added if needed for more sophisticated mesh generation

/**
 * Denormalizes ShipD parameters from 0-1 range to physical units
 */
function denormalizeParameters(
  shipdVector: number[],
  metadata: ShipDParameterMetadata[]
): Record<number, number> {
  const denormalized: Record<number, number> = {};

  for (let i = 0; i < shipdVector.length; i++) {
    const param = metadata.find((m) => m.parameterIndex === i);
    const normalized = shipdVector[i];

    if (param && param.min != null && param.max != null) {
      // Linear denormalization: physical = min + (max - min) * normalized
      const physical = param.min + (param.max - param.min) * normalized;
      denormalized[i] = physical;
    } else {
      // No metadata - use normalized value as-is
      denormalized[i] = normalized;
    }
  }

  return denormalized;
}

/**
 * Generates offsets for a single station based on ShipD parameters
 */
function generateStationOffsets(
  stationPos: number,
  region: "bow" | "midship" | "stern",
  denormalized: Record<number, number>,
  _lppM: number,
  beamM: number,
  draftM: number,
  _metadata: ShipDParameterMetadata[]
): Record<number, number> {
  const offsets: Record<number, number> = {};

  // Always start with keel point (height=0, half-breadth=0) to close the bottom
  offsets[0] = 0;

  // Generate offsets at various heights (including freeboard above waterline)
  const heightSteps = 20;
  const maxHeight = draftM * 1.35; // Include 35% freeboard above waterline (more realistic proportions)

  for (let h = 1; h <= heightSteps; h++) {
    // Start from 1 to avoid duplicate keel point
    const height = (h / heightSteps) * maxHeight; // Height from keel to above waterline

    let halfBreadth = 0;

    if (region === "bow") {
      // Bow section: use Beta (flare), Cdrft (deadrise), Rc (curvature), Rk (knuckle), Kappa_bow (convex/concave)
      const beta = denormalized[8]; // Flare angle (degrees)
      const rc = denormalized[9]; // Curvature coefficient (0-1)
      const rk = denormalized[10]; // Knuckle coefficient (0-1)
      const kappaBow = denormalized[14]; // Curvature type (-1 to 1, concave to convex)
      const cdrft = denormalized[19]; // Deadrise angle (degrees)

      const heightRatio = height / draftM;

      // CORRECT VERTICAL PROFILE: Narrow at keel, wide at waterline
      if (height <= draftM) {
        // BELOW WATERLINE: Expand from narrow keel to wide waterline

        // 1. Calculate keel width (reduced by deadrise)
        const deadriseReduction = Math.tan((cdrft * Math.PI) / 180) * (draftM - height);
        const keelHalfBreadth = Math.max(0, (beamM / 2) * 0.1); // Keel is ~10% of beam

        // 2. Expansion curve from keel to waterline
        // Higher Rc = fuller (straighter expansion), Lower Rc = finer (more curved)
        const curvePower = 2.5 - rc * 1.5; // Range: 1.0 (full) to 2.5 (fine)
        const expansionRatio = Math.pow(heightRatio, 1 / curvePower);

        // 3. Interpolate from keel to max beam
        let baseHalfBreadth =
          keelHalfBreadth +
          (beamM / 2 - keelHalfBreadth - deadriseReduction * 0.3) * expansionRatio;

        // 4. Apply knuckle effect (hard chine)
        if (rk > 0.3) {
          const knuckleHeight = 0.5; // Knuckle at mid-height
          const knuckleRange = 0.2;
          if (Math.abs(heightRatio - knuckleHeight) < knuckleRange) {
            const knuckleFactor = 1 - Math.abs(heightRatio - knuckleHeight) / knuckleRange;
            baseHalfBreadth *= 1 + rk * knuckleFactor * 0.15;
          }
        }

        // 5. Apply convex/concave control
        if (Math.abs(kappaBow) > 0.1) {
          const convexEffect = kappaBow * Math.sin((heightRatio * Math.PI) / 2) * 0.1;
          baseHalfBreadth *= 1 + convexEffect;
        }

        halfBreadth = Math.max(0, baseHalfBreadth);
      } else {
        // ABOVE WATERLINE: Apply flare (widen)
        const aboveWLHeight = height - draftM;

        // Start at waterline beam
        let baseHalfBreadth = beamM / 2;

        // Add flare effect
        if (beta > 5) {
          const flareExpansion = Math.tan((beta * Math.PI) / 180) * aboveWLHeight;
          baseHalfBreadth += flareExpansion * 0.2;
        }

        halfBreadth = Math.max(0, baseHalfBreadth);
      }
    } else if (region === "midship") {
      // Midship section: use bit_EP_S (sheer), bit_EP_T (tumblehome)
      const bitEPS = denormalized[20] > 0.5; // Sheer extrusion
      const bitEPT = denormalized[21] > 0.5; // Tumblehome

      const heightRatio = height / draftM;

      // CORRECT VERTICAL PROFILE: Midship typically parallel below waterline
      if (height <= draftM) {
        // BELOW WATERLINE: Gentle expansion from keel to waterline
        // Midship has less deadrise, more parallel sides

        const keelHalfBreadth = (beamM / 2) * 0.2; // Midship keel ~20% of beam (wider than bow)

        // Simple gentle expansion (midship is typically straighter)
        const expansionRatio = Math.pow(heightRatio, 0.8); // Gentle curve
        const baseHalfBreadth = keelHalfBreadth + (beamM / 2 - keelHalfBreadth) * expansionRatio;

        halfBreadth = baseHalfBreadth;
      } else {
        // ABOVE WATERLINE
        const aboveWLHeight = height - draftM;
        const freeboard = draftM * 0.35; // Match total freeboard (35%)
        const aboveWLRatio = Math.min(aboveWLHeight / freeboard, 1.0);

        let baseHalfBreadth = beamM / 2;

        // Sheer (outward curve at deck)
        if (bitEPS && aboveWLRatio > 0.6) {
          baseHalfBreadth *= 1 + ((aboveWLRatio - 0.6) / 0.4) * 0.08;
        }

        // Tumblehome (inward curve at deck)
        if (bitEPT && aboveWLRatio > 0.5) {
          baseHalfBreadth *= 1 - ((aboveWLRatio - 0.5) / 0.5) * 0.15;
        }

        halfBreadth = baseHalfBreadth;
      }
    } else {
      // Stern section: use Atrans, Beta_trans, Bc_trans, Rc_trans, Rk_trans, Kappa_stern
      const atrans = denormalized[22]; // Transom area coefficient
      const kappaStern = denormalized[24]; // Curvature type (-1 to 1, concave to convex)
      const betaTrans = denormalized[27]; // Stern rake angle
      const bcTrans = denormalized[28]; // Transom width ratio
      const rcTrans = denormalized[29]; // Stern curvature coefficient
      const rkTrans = denormalized[30]; // Stern knuckle coefficient

      const heightRatio = height / draftM;

      // CORRECT VERTICAL PROFILE: Similar to bow but with stern characteristics
      if (height <= draftM) {
        // BELOW WATERLINE: Expand from narrow keel to wide waterline

        const keelHalfBreadth = (beamM / 2) * 0.15; // Stern keel slightly wider than bow

        // Curvature expansion
        const curvePower = 2.5 - rcTrans * 1.5; // Range: 1.0 (full) to 2.5 (fine)
        const expansionRatio = Math.pow(heightRatio, 1 / curvePower);

        let baseHalfBreadth = keelHalfBreadth + (beamM / 2 - keelHalfBreadth) * expansionRatio;

        // Transom effect (flat stern) - only near the very aft
        if (stationPos < 0.15 && atrans > 0.5) {
          const transomWidth = beamM * bcTrans;
          const transomBlend = (0.15 - stationPos) / 0.15; // Blend over aft 15%
          baseHalfBreadth =
            baseHalfBreadth * (1 - transomBlend * atrans) +
            (transomWidth / 2) * transomBlend * atrans;
        }

        // Stern knuckle
        if (rkTrans > 0.3 && heightRatio > 0.3 && heightRatio < 0.6) {
          const knuckleFactor = 1 - Math.abs(heightRatio - 0.45) / 0.15;
          baseHalfBreadth *= 1 + rkTrans * knuckleFactor * 0.12;
        }

        // Apply convex/concave control
        if (Math.abs(kappaStern) > 0.1) {
          const convexEffect = kappaStern * Math.sin((heightRatio * Math.PI) / 2) * 0.1;
          baseHalfBreadth *= 1 + convexEffect;
        }

        halfBreadth = Math.max(0, baseHalfBreadth);
      } else {
        // ABOVE WATERLINE: Rake effect
        const aboveWLHeight = height - draftM;
        let baseHalfBreadth = beamM / 2;

        // Apply rake (aft overhang)
        if (betaTrans > 5 && stationPos < 0.2) {
          const rakeExpansion = Math.tan((betaTrans * Math.PI) / 180) * aboveWLHeight;
          baseHalfBreadth += rakeExpansion * 0.15;
        }

        halfBreadth = Math.max(0, baseHalfBreadth);
      }
    }

    // LONGITUDINAL SCALING: Apply taper based on station position and region
    // This creates the actual bow/stern taper (hull narrows toward ends)
    let longitudinalScale = 1.0;

    if (region === "bow") {
      // Bow region: Taper from full beam at bowStart to centerline at bow tip (pos=1.0)
      // Need bow boundaries - use vector directly (already ratios)
      const lb = shipdVector[1] ?? 0.3; // Bow length ratio
      const ls = shipdVector[2] ?? 0.3; // Stern length ratio
      const bowStart = 1.0 - lb - ls + ls; // Start of bow region

      if (stationPos >= bowStart) {
        // Position within bow region: 0 = bow start (full beam), 1 = bow tip (centerline)
        const bowPos = (stationPos - bowStart) / (1.0 - bowStart);
        // Taper: quadratic for smooth curve
        longitudinalScale = Math.pow(1.0 - bowPos, 2.0);
      }
    } else if (region === "stern") {
      // Stern region: Taper from centerline at stern tip (pos=0.0) to full beam at midStart
      const ls = shipdVector[2] ?? 0.3; // Stern length ratio (already a ratio)

      if (stationPos <= ls) {
        // Position within stern region: 0 = stern tip (centerline), 1 = stern end (full beam)
        const sternPos = stationPos / ls;
        // Taper: quadratic for smooth curve
        longitudinalScale = Math.pow(sternPos, 2.0);
      }
    }
    // Midship region: longitudinalScale = 1.0 (no taper, full beam)

    // Apply longitudinal scaling to half-breadth
    halfBreadth = halfBreadth * longitudinalScale;

    offsets[height] = Math.max(0, halfBreadth);
  }

  // Ensure we have a point at the deck level (draftM) to close the top
  if (!(draftM in offsets)) {
    const maxHeight = Math.max(...Object.keys(offsets).map(Number));
    const maxHalfBreadth = offsets[maxHeight];
    offsets[draftM] = maxHalfBreadth * 0.95; // Slightly narrower at deck
  }

  return offsets;
}

/**
 * Generates bulb offsets for a station in the bow region
 */
function generateBulbOffsets(
  stationPos: number,
  shipdVector: number[],
  _lppM: number,
  beamM: number,
  draftM: number
): Record<number, number> {
  const offsets: Record<number, number> = {};

  // Bulb parameters - these are ratios, use vector directly
  const lbb = shipdVector[33]; // Bulb length ratio
  const hbb = shipdVector[34]; // Bulb height ratio
  const bbb = shipdVector[35]; // Bulb width ratio
  const lbbm = shipdVector[36]; // Bulb asymmetry (fore/aft position) - NOW USED!
  const rbb = shipdVector[37]; // Bulb fillet radius - NOW USED!

  // Bulb is only in forward section
  const bowStart = 1.0 - (shipdVector[1] ?? 0.3) - (shipdVector[2] ?? 0.3); // Start of bow region
  const bulbExtent = lbb * 0.7; // Bulb extends forward

  if (stationPos > bowStart && stationPos < bowStart + bulbExtent) {
    // Position within bulb (0 = start, 1 = forward end)
    const bulbPos = (stationPos - bowStart) / bulbExtent;

    // Apply asymmetry: lbbm shifts max bulb diameter fore/aft
    const asymmetryShift = (lbbm - 0.5) * 0.3; // -0.15 to +0.15
    const adjustedPos = Math.max(0, Math.min(1, bulbPos + asymmetryShift));

    const bulbHeight = hbb * draftM;
    const bulbWidth = bbb * beamM;

    // Longitudinal profile: use fillet radius to control shape
    // Higher rbb = rounder, lower rbb = more pointed
    const longitudinalExp = 1.5 + rbb * 1.0; // 1.5-2.5
    const longitudinalProfile = Math.pow(
      1 - Math.pow(adjustedPos, longitudinalExp),
      1 / longitudinalExp
    );

    const heightSteps = 12;
    for (let h = 0; h <= heightSteps; h++) {
      const height = (h / heightSteps) * bulbHeight;
      const heightRatio = height / bulbHeight;

      // Vertical profile: ellipsoid with fillet control
      const verticalExp = 1.8 + (1 - rbb) * 0.5; // 1.8-2.3
      const verticalProfile = Math.pow(1 - Math.pow(heightRatio, verticalExp), 1 / verticalExp);

      const halfBreadth = (bulbWidth / 2) * longitudinalProfile * verticalProfile;
      offsets[height] = Math.max(0, halfBreadth);
    }
  }

  return offsets;
}
